### ISSUE TITLE
Device UI does not draw with proper values when switching visible Chain in a Group

### ISSUE THREAD

**Issue by TheMarkTwo** [mat1jaczyyy/apollo-studio#1]
**Describe the bug**
Delay ui doesnt update after different chain selection

**To Reproduce**
Change the duration of the delay and then change to a different chain, go back and the UI doesnt update

**Expected behavior**
It should update

**Screenshots**
![image](https://user-images.githubusercontent.com/45077262/48572476-d0b06a00-e909-11e8-892a-c50d868e2960.png)
![image](https://user-images.githubusercontent.com/45077262/48572487-d60db480-e909-11e8-8972-611a4c1dad04.png)

**Your setup**
Describe the system you are running on. Usually, just the OS is fine.
Windows 10

**Comment by vaaski** [comment]
thanks, will fix that
