### ISSUE TITLE
Splash Window Improvements

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#102]
- [x] Tabs

File:
- [x] List of recently opened files, sorted by last opened

Learn:
- [x] Links to documentation
- [x] Links to tutorial videos

News:
- [ ] Recent Blogpost
- [x] Update Changelog

**Comment by TheLifeGamingYT** [comment]
Hey, I think you should close this. You already added a section for a Recent Blogpost.

**Comment by mat1jaczyyy** [comment]
@TheLifeGamingYT does it contain the blogpost though

**Comment by TheLifeGamingYT** [comment]
yes
