### ISSUE TITLE
Crash upon playing single-frame .gif in Pattern

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#103]
### Description
Crash when an imported .gif in Pattern has only one frame, therefore being loaded with length 0ms and the Pattern device gets triggered.

### To Reproduce
Load single-frame .gif into Pattern (length 0ms) and trigger the Pattern.

### Expected behavior
No Crash.

### Your setup
Windows 10 (1803)
Apollo Beta Build 3 (e77ee24)

### Additional context
[tested with this single-frame gif]
![white](https://user-images.githubusercontent.com/38407233/58441265-e97fb080-80e0-11e9-9345-675b6bb51714.gif)

**Comment by mat1jaczyyy** [comment]
Almost didn't see the white gif lmao
