### ISSUE TITLE
Chain Output Indicator

### ISSUE THREAD

**Issue by TheMarkTwo** [mat1jaczyyy/apollo-studio#106]
### Describe the solution you'd like
Display which chain is outputing

**Comment by mat1jaczyyy** [comment]
I don't think I'll be implementing this for one reason - every time a Signal passes through, I need to update the UI thread, which costs a lot of performance. Just like using a Preview device can cause lags, these indicators would be causing the lag all the time.

**Comment by mat1jaczyyy** [comment]
Let's make this a toggleable option, which should be disabled while performing.
