### ISSUE TITLE
Title text alignment of window is unsightly

### ISSUE THREAD

**Issue by RealAsianNoodles** [mat1jaczyyy/apollo-studio#107]
### Description
The alignment of the title text of a window is unsightly - with respect to the "plus" symbol (+), the text is misaligned 

### To Reproduce
Open Apollo

### Screenshots

<img width="947" alt="image" src="https://user-images.githubusercontent.com/18259598/58741622-44adfc00-846f-11e9-96b0-6381565e3e02.png">

### Your setup
MacOS Mojave 10.14.5, Apollo b5

**Comment by mat1jaczyyy** [comment]
We can do this by comparing widths of the Text control and the sides.
