### ISSUE TITLE
Integrated gif-to-light converter

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#11]
A drag-and-drop device that allows .gif files to be imported and converted to light information (basically Schlegel Flegels tool for gif2midi as a device).
Additional features of this device compared to the gif2midi python script might be things like changing playback speed, scaling and moving, resulting in new, more interesting lightshows across the Launchpad.

-----
Alternatively, one could just use SFs tool and import the .mid into the upcoming midi file player, but importing .gifs and manipulating parameters live seems more fun and less work for the end user.

**Comment by mat1jaczyyy** [comment]
Implemented by 481a1c99e3bda0c5f1fd68055ee50da9df879a13.
