### ISSUE TITLE
Crash on startup (Common.xaml can't be found)

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#118]
### Description
Apollo crashes on startup due to not found file /Themes/Common.xaml

### To Reproduce
Launch Apollo Build 8 or commits up to 6a45c32.

### Expected behavior
No crash.

### Your setup
Windows 10 (1803)
Apollo Beta 8 (6a45c32)

### Additional context
`https://pastebin.com/BijwAvch`

**Comment by mat1jaczyyy** [comment]
Interesting, definitely wasn't getting this when testing, will have a look.
