### ISSUE TITLE
Crash when decoding invalid Binary

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#119]
### Description
Apollo crashes when an invalid .approj file is loaded.

### To Reproduce
Load invalid .approj file into Apollo.

### Expected behavior
No crash.

### Your setup
Windows 10 (1803)
Apollo Beta 8 (6a45c32)

### Additional context
`Exception has occurred: CLR/System.IndexOutOfRangeException
Eine Ausnahme vom Typ "System.IndexOutOfRangeException" ist in Apollo.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.: 'Index was outside the bounds of the array.'
   bei Apollo.Binary.Decoder.DecodeID(BinaryReader reader) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Binary\Decoder.cs: Zeile21
   bei Apollo.Binary.Decoder.Decode(BinaryReader reader, Int32 version, Type ensure, Boolean root) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Binary\Decoder.cs: Zeile32
   bei Apollo.Binary.Decoder.Decode(Stream input, Type ensure) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Binary\Decoder.cs: Zeile27
   bei Apollo.Windows.SplashWindow.<Open>d__6.MoveNext() in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Windows\SplashWindow.cs: Zeile70`

**Comment by mat1jaczyyy** [comment]
Assuming same issue for Importing (aptrk, apchn, apdev) as well.
