### ISSUE TITLE
Apollo loads (older) project files with all devices muted by default

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#120]
### Description
When you open a non-empty projects (from an older version of Apollo with no muting), all(?) devices will be muted by default.

### To Reproduce
Load project from around Beta Build 5 in Beta Build 8.

### Expected behavior
Unmuted devices as they were in older versions.

### Your setup
Windows 10 (1803)
Apollo Beta 8 (6a45c32)

**Comment by mat1jaczyyy** [comment]
https://github.com/mat1jaczyyy/apollo-studio/blob/6a45c32dac3b4ae6be1cbb343df3a225b6fe1dce/Apollo/Binary/Decoder.cs#L118

oh.
