### ISSUE TITLE
Garbage disposal doesn't deallocate memory upon (re)loading chains into viewer

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#129]
### Is your feature request related to a problem? Please describe.
When (re)opening bigger chains Apollo keeps allocating memory. This leads to a possible increase to multiple GBs of used memory through working on a project over the span days without closing Apollo in between sessions.

### Describe the solution you'd like
More efficient garbage disposal for optimized workflow and speed.

### Describe alternatives you've considered
Closing Apollo and reopening the project seems to be a workaround for the time being.

### Additional context
![memory](https://user-images.githubusercontent.com/38407233/59292404-4bade900-8c7d-11e9-85fb-6493a16dd3d5.png)

**Comment by mat1jaczyyy** [comment]
Nice catch

**Comment by mat1jaczyyy** [comment]
Events that are on logic need to get unsubscribed from when viewers detach. If this does not help the issue, it's likely related to Avalonia.

**Comment by mat1jaczyyy** [comment]
Fixed by 86c5cec.
