### ISSUE TITLE
Having the arrow keys add frames the same as launchpad gestures

### ISSUE THREAD

**Issue by TheSillySpy** [mat1jaczyyy/apollo-studio#137]
Launchpad Gestures include the feature of having the next frame shortcut add a new frame automatically. 

Having a setting that allows the same for the UI would be a good add on.

Beta 10

**Comment by mat1jaczyyy** [comment]
The issue comes from having to distinguish between gestures which affect the currently visible frame (marked in bold) and the keyboard shortcts which affect the highlighted selection. We will consider unifying this behavior.
