### ISSUE TITLE
additional windows don't pop up above apollo if it's been moved on another screen

### ISSUE THREAD

**Issue by vaaski** [mat1jaczyyy/apollo-studio#14]
### Description

Windows (e.g.) settings launch on the screen Apollo has originally been launched on, not the one Apollo has been moved to.

### To Reproduce

Open Apollo on screen A, move window to screen B and click something that triggers another window to open.

### Expected behavior

The window should pop up above the Apollo window

### Screenshots

![sad](https://user-images.githubusercontent.com/17879327/55173001-401d4c80-517b-11e9-8085-670d97a37b18.jpg)

### Your setup

Apollo (avalonia-ui)

### Additional context

Other than that, looks really good ;)

edit: my fat finger slipped on ctrl while making a new line and i wasn't done

**Comment by mat1jaczyyy** [comment]
Fixed by 5ded3b11483fd1519eb1eb44184215dff049fc34.
