### ISSUE TITLE
Having a mute shortcut to 0

### ISSUE THREAD

**Issue by TheSillySpy** [mat1jaczyyy/apollo-studio#140]
Possibly making it so that you can press the 0 key in order to mute effects (Once again similar to Ableton)

Either making this an option or a standard feature would be fine.

A possible alternative to all the shortcut features I've stated before is including some sort of custom keybindings menu if possible. 

Ex) 
F - Opens Fade
G - Creates Groups
H - Opens Hues
D - Delay

All of which being fully customizable would create a much more specialized workflow built for each individual.

Apollo Beta Version 11

**Comment by mat1jaczyyy** [comment]
Ctrl+M is used to Mute/Unmute, is this shortcut enough or do you feel we need to expand to 0?

Device inserting isn't feasible as we have the question of where it would insert to.

**Comment by TheSillySpy** [comment]
Pressing 0 is more a preference thing that has been a habit developed from Ableton. Might just be me that has that habit but I'm just used to it.
