### ISSUE TITLE
Pattern displayed duration value bug

### ISSUE THREAD

**Issue by M4kI9H7** [mat1jaczyyy/apollo-studio#143]
### Description
Pattern's left panel where each chain's duration is displayed
When a chain is deleted, its displayed duration value will passed onto the previous chain's displayed value.
It does not change the previous chain's actual duration value, and will update after reopening Pattern editor/Ctrl + Z and Ctrl + Y

### To Reproduce
Described above

### Expected behavior
n/a

### Screenshots

![bandicam 2019-06-15 19-00-47-729](https://user-images.githubusercontent.com/49873818/59549956-f9800700-8f9f-11e9-9878-6e45993235d9.jpg)

### Your setup

Windows, apollo-b11

### Additional context

n/a

**Comment by mat1jaczyyy** [comment]
Nice catch.
