### ISSUE TITLE
Being able to rename Devices to keep organized.

### ISSUE THREAD

**Issue by TheSillySpy** [mat1jaczyyy/apollo-studio#146]
### Is your feature request related to a problem? Please describe.
Don't know whether it is a feature or not but I cannot rename a device. Being able to rename groups "Main Pages", "Long Light effect", "Page 3" might come in handy. Same could possibly go for fades or other plugins. Could make things more organized and easy to read. Once again could just be my opinion.

### Describe the solution you'd like
Make it so that you could rename devices.

### Additional context
Windows 10, Apollo Beta Ver. 11

**Comment by mat1jaczyyy** [comment]
With the current infrastructure, this is insanely hard to do, since we built Apollo believing there isn't much of a use case for this. We will sadly not be implementing this feature request.
