### ISSUE TITLE
Switch processing order

### ISSUE THREAD

**Issue by TrypticonLP** [mat1jaczyyy/apollo-studio#148]
I encountered this bug while using the "Switch" device on page 1 to switch to page 2. The problem arose when I pressed the button that changed the page, it would play the light on that button page 1 and the other light on that button on page 2 at the same time. 

Obviously only the light on page 1 should be played but it plays the light on page 2 with the same button press. I've tried changing the order the "Switch" device is situated in the chain, but it doesn't make a difference.

Apollo playing both lights at the same time
![Screen Shot 2019-06-16 at 1 39 00 PM](https://user-images.githubusercontent.com/51866977/59567479-46192000-903c-11e9-8fed-a03cca3d7f9e.png)

My chain setup if helpful
![Screen Shot 2019-06-16 at 1 37 56 PM](https://user-images.githubusercontent.com/51866977/59567481-6052fe00-903c-11e9-8e43-915fab314f7e.png)

**Comment by mat1jaczyyy** [comment]
Put switch right after your KeyFilter. Should work correctly.

**Comment by TrypticonLP** [comment]
Already tried that, still having the same issue

**Comment by mat1jaczyyy** [comment]
Can you attach a project file that shows the issue?

**Comment by TrypticonLP** [comment]
[Teminite.approj.zip](https://github.com/mat1jaczyyy/apollo-studio/files/3294433/Teminite.approj.zip)

**Comment by mat1jaczyyy** [comment]
Yes, this is an issue. We will develop a fix.

**Comment by mat1jaczyyy** [comment]
You should still, however, as a best practice, keep your Switch device before any light effect, but after the KeyFilter.
