### ISSUE TITLE
Redesign Device Context Menu

### ISSUE THREAD

**Issue by TrypticonLP** [mat1jaczyyy/apollo-studio#150]
Title is self explanatory. When window is too close to the bottom of the screen the device dropdown gets cut off which would facilitate the need for a scroll bar or a dropdown flipper.

**Comment by mat1jaczyyy** [comment]
I'm aware of the Device Dropdown being quirky. I've considered some solutions, not sure what I'll settle on yet.

**Comment by mat1jaczyyy** [comment]
I think we'll go for [submenus](https://stackoverflow.com/questions/18590730/wpf-submenu-for-context-menu).
