### ISSUE TITLE
Frame advance hotkey change request

### ISSUE THREAD

**Issue by TrypticonLP** [mat1jaczyyy/apollo-studio#151]
Currently the hotkey for advancing frames in the pattern editor is "ins" but this key does not exist (at least explicitly) on all keyboards (i.e. my Macbook keyboard). 

For ease of use across all platforms I think changing the hotkey to something that is consistent across full and compact keyboards would be useful. Perhaps using the + key would be appropriate for this specific action.

**Comment by mat1jaczyyy** [comment]
This will change as part of #137, so I'm considering it a duplicate issue. Always check for similar issues and add a comment if unsure.
