### ISSUE TITLE
Hold - Fade combination infinite lights problem

### ISSUE THREAD

**Issue by TrypticonLP** [mat1jaczyyy/apollo-studio#152]
### Description
When a Hold is used in conjunction with a Fade device the light created will continue indefinitely even though the infinite switch on the Hold device is unchecked.

### Expected behavior
Light effect should end in accordance with the rate knobs on both the Hold and Fade devices

### My setup
Apollo Beta 12, MacOS 10.13.1
![Screen Shot 2019-06-17 at 5 53 52 PM](https://user-images.githubusercontent.com/51866977/59639341-f5332580-9128-11e9-84e1-ef4193631019.png)

**Comment by rpgaleksy** [comment]
In Beta 12 (Win 10 1803) Hold actually holds incoming notes infinitely on its own, no need for a Fade device.

dev pls fix
