### ISSUE TITLE
Pattern: Option to repeat pattern X times

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#156]
### Is your feature request related to a problem? Please describe.
Kinda, saving a long repeating pattern is quite redundant and the loop feature is more useful for dynamic changes in Pattern length.
Meanwhile, a direct "Repeat X times" option would be useful in cases with a fixed effect length that would contain unnecessary repetitions otherwise.

### Describe the solution you'd like
Repeat option as playback mode, the name might be confusing with Loop though, needs some more though.

### Describe alternatives you've considered
Using Hold and existing Loop mode. Quite impractical for effects longer than 4/1 * 400% (yes, free time choice is possible but still too tedious than just specifying a repetition amount).

**Comment by mat1jaczyyy** [comment]
This is a pain in the ass to implement, and can already be done 2 ways by duplicating or using a Hold + Loop. You should work around this limitation.

There are many reasons why: the Timers for the buffered playback engine already need to know how to handle 3 different kinds of behaviors, adding more would raise serious questions as to how we should handle certain cases. For example, what if the last frame is infinite? How should it know if it's time to go over to the first frame again? Etc.

Won't fix.

**Comment by rpgaleksy** [comment]
Ok then, workaround it is.
I'll still look for my own way how this could be implemented without a large mess though.

**Comment by mat1jaczyyy** [comment]
Will implement this after all.
