### ISSUE TITLE
Pattern device Ctrl+A and Delete

### ISSUE THREAD

**Issue by M4kI9H7** [mat1jaczyyy/apollo-studio#159]
### Is your feature request related to a problem? Please describe.
Since Pattern's frame shouldn't be empty, if there's only one frame, it won't be deleted.
However, trying to delete all frames with Ctrl+A and Delete selects all frames, Delete won't function at all, because of the reason described above.
I think this isn't exactly an ideal for shortcuts, especially Ctrl+Click isn't implemented yet.

### Describe the solution you'd like
Maybe the only frame clears to default when it gets deleted, or such things.

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by mat1jaczyyy** [comment]
This is intended behavior, because it is not possible to have a Pattern device that does not contain at least one frame. The application cannot guess which of one of these Frames the user would intend to keep.
