### ISSUE TITLE
Auto Update with ApolloHelper.exe thingy

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#164]
### Describe the solution you'd like
Have an update notification on splash screen that launches auto-updater process, which then downloads the new version, kills Apollo.exe process, unpacks and applies changes, restarts Apollo, then kills itself.

### Describe alternatives you've considered
Manual downloading and installing updates. lol

**Comment by mat1jaczyyy** [comment]
Will implement this after #102.
