### ISSUE TITLE
Apollo translations

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#166]
### Describe the solution you'd like
Chooseable languages for local text output in UI.

### Describe alternatives you've considered
no translations.

### Additional context
gay

**Comment by mat1jaczyyy** [comment]
We will not support translations.

**Comment by mat1jaczyyy** [comment]
Conflicted on this one as more people brought it up. Will reopen for the sake of a live issue, but no promises yet at least for Release.

**Comment by mat1jaczyyy** [comment]
After dealing with translations in a different project, I've ultimately decided not to support translations. They're simply too quirky to deal with, especially in a codebase this large, and it fragments the user base. Closing for good.
