### ISSUE TITLE
Automations

### ISSUE THREAD

**Issue by TheMarkTwo** [mat1jaczyyy/apollo-studio#169]

**Comment by mat1jaczyyy** [comment]
Can you describe your use case?

**Comment by mat1jaczyyy** [comment]
Assuming this means Ableton-like automations, this isn't something that can be implemented without changing the infrastructure of Apollo considerably. Mapping to a parameter wouldn't work nicely anyway with the Undo history, just like it's messy in Ableton Live, and I'd like to avoid that.
