### ISSUE TITLE
Add button is difficult to click/make appear.

### ISSUE THREAD

**Issue by TruffleLaunchpad** [mat1jaczyyy/apollo-studio#17]
When going to 'summon' the add button, sometimes the button never appears or isn't easy to click. 
(I'm testing with MacOS)

**Comment by mat1jaczyyy** [comment]
Check out the new Build 9, let me know if it is any better.

**Comment by mat1jaczyyy** [comment]
Fixed by f081abe702930d23fe2f2044682326fdf81f9acc.
