### ISSUE TITLE
Clear undo history (saving RAM usage)

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#172]
### Is your feature request related to a problem? Please describe.
RAM usage can still be quite high due to keeping the whole undo history in memory.

### Describe the solution you'd like
A "clear history" button that deletes the current history when not needed anymore would fix this issue.

**Comment by mat1jaczyyy** [comment]
In addition to manually clearing, it might be possible to configure a maximum number of history entries you want stored, and even automatic cleaning when total PC RAM usage reaches around 90%.
