### ISSUE TITLE
Muted state of a Device won't be kept after Copy&Paste

### ISSUE THREAD

**Issue by M4kI9H7** [mat1jaczyyy/apollo-studio#177]
### Description
Copied Devices in muted state won't keep their muted state after Copy, Cut&Paste/Export&Imported

### To Reproduce
Described above.

### Expected behavior
Keep their muted state when Copied/Cut/Exported.

### Screenshots
n/a

### Your setup
Windows, apollo-b16
### Additional context
However, Duplicate seems to be working as intended.
and Chains in Group device works well.

**Comment by mat1jaczyyy** [comment]
Oof, big bug. Turns out the fix for this breaks existing .apdev exported files

**Comment by mat1jaczyyy** [comment]
Nvm, it actually doesn't, but the old files will load without the muted state since it isn't being written down.
