### ISSUE TITLE
Crash after pressing play with a 0% gate in the pattern view

### ISSUE THREAD

**Issue by EjectUSB** [mat1jaczyyy/apollo-studio#18]
### Description
Crash after trying to play a pattern with a gate of 0% in the pattern view

### To Reproduce

1. Open up a new project
2. Open your launchpad track
3. Open up a new pattern 
4. Place a note somewhere
5. set the gate to 0%
6. Press play

### Expected behavior
An error message showing you can't do that, the gate only going to 1% or the light not showing up at all.

### Screenshots
Video: https://streamable.com/a26wn

### Your setup
Windows 10, Running apollo build 9 (up and untill commit 51255c504a5ce51b130d6dd8469c6cd3e85b5522) With an launchpad MKII

**Comment by mat1jaczyyy** [comment]
Reproduced. Also happens with Delay and Hold, and other devices that utilize Gate
