### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by TheLifeGamingYT** [mat1jaczyyy/apollo-studio#181]
### Is your feature request related to a problem? Please describe.
The problem is that if I want to make a complicated light effect that I use frequently, I need to remake it every time.

### Describe the solution you'd like
Like Ableton Live's effects, I would really like if you could save presets as files for effects like Fade, Pattern,... 

### Describe alternatives you've considered
You could make more Apollo Projects and copy and paste, but it's very inefficient.

### Additional context
Add samples functionality (if you can do this)

**Comment by mat1jaczyyy** [comment]
Can't you just right click a Device and Export? Right click anywhere to import

**Comment by TheLifeGamingYT** [comment]
Really?

**Comment by TheLifeGamingYT** [comment]
Sorry

**Comment by TheLifeGamingYT** [comment]
But can you do it with entire chains or groups?

**Comment by mat1jaczyyy** [comment]
Yes you can export Groups or even individual Chains into files.

**Comment by mat1jaczyyy** [comment]
Marking issue as solved.
