### ISSUE TITLE
Color accuracy in Pattern and similar devices

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#184]
### Description
Device like Pattern currently don't display color as they would actually appear on the Launchpad.
Creating a gradient over the whole virtual Launchpad for testing for example results in a very gradually saturating color with a harsh cut at the maximum color, at which the fully saturated color appears. When looking at the Launchpad, it displays the gradient with no problem.

### To Reproduce
Fill the whole grid in Pattern with a gradient and play the pattern.

### Expected behavior
True-er to life representation of color on the display.

### Screenshots
![colors](https://user-images.githubusercontent.com/38407233/60394586-00258700-9b27-11e9-98b9-6b5b0a78390b.png)

### Your setup
Windows 10 (1803)
Apollo Beta 17

**Comment by mat1jaczyyy** [comment]
Can you attach this pattern?
