### ISSUE TITLE
Diagonal mode doesn't render Launchpads anymore

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#189]
### Description
When Launchpad mode is diagonal all on-screen Launchpad don't render.

### To Reproduce
Set Launchpad mode to diagonal mode and open virtual Launchpad or Keyfilter for example.

### Expected behavior
Correct rendering.

### Screenshots
![diagonallp](https://user-images.githubusercontent.com/38407233/60419336-55c06900-9be5-11e9-9e99-860dabd8ce9e.PNG)

### Your setup
Windows 10 (1803)
Apollo Beta 18

**Comment by rpgaleksy** [comment]
Apparently, the Pattern window doesn't show any Launchpad at all now as well, no matter the mode.

**Comment by mat1jaczyyy** [comment]
![image](https://user-images.githubusercontent.com/13300194/60439453-34767180-9c13-11e9-99e3-4aa9ed5219d5.png)
Can't reproduce?

**Comment by mat1jaczyyy** [comment]
German locale reeeeeeeeeeeee
