### ISSUE TITLE
Flip Device

### ISSUE THREAD

**Issue by TheMarkTwo** [mat1jaczyyy/apollo-studio#19]
### Is your feature request related to a problem? Please describe.
It isnt related to a problem, it is a device request

### Describe the solution you'd like
Add a flip device that lets you flip lights (patterns)

### Describe alternatives you've considered
Add a option to flip on the pattern device

### Additional context
sans undertale

**Comment by mat1jaczyyy** [comment]
There will be two separate devices, Flip having options to do Horizontal, Vertical, +Diagonal and -Diagonal; and Rotate having options to do 90°, 180°, and 270°.

**Comment by mat1jaczyyy** [comment]
Solved by c2239b92a49cbec5d1c1e7b16bc914c2c5461873 and 9b9b9bef9daa7c13faa9643b7ae27fc0d7c63082.
