### ISSUE TITLE
Pad Release is sent to new Page after Switch

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#190]
### Description
See title.

### To Reproduce
Put Hold device with infinite setting after Fade and play effect. Doesn't happen all the time.

### Expected behavior
No crash.

### Screenshots
![faho](https://user-images.githubusercontent.com/38407233/60472389-fd32af80-9c68-11e9-8b40-ffc603b07df3.PNG)

### Your setup
Windows 10 (1803)
Apollo Beta 18

### Additional context
[crashdump-1562023507-exception.log](https://github.com/mat1jaczyyy/apollo-studio/files/3347649/crashdump-1562023507-exception.log)

**Comment by mat1jaczyyy** [comment]
Fade -> Hold has nothing to do with this. There is a Hold in your project with Release enabled that is picking up a button release when there wasn't ever a press. Perhaps because of a Switch triggering?

**Comment by mat1jaczyyy** [comment]
Minimal reproduction
[crass(1).zip](https://github.com/mat1jaczyyy/apollo-studio/files/3351896/crass.1.zip)

**Comment by mat1jaczyyy** [comment]
Fixed by 5e3dd13.
