### ISSUE TITLE
Recent projects get cleared when closing and reopening Apollo

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#193]
### Description
See title.

### To Reproduce
Open a project and close the project (exit to opening screen with big logo), recent projects are non-empty.
Close Apollo and restart it, recent projects are empty again.

### Expected behavior
Recent projects stay saved.

### Your setup
Windows 10 (1803)
Apollo Beta 19

**Comment by mat1jaczyyy** [comment]
Fixed by 09fbf11.
