### ISSUE TITLE
API crashes if no Launchpads are connected, leaving APP hanging

### ISSUE THREAD

**Issue by Ev1ternity** [mat1jaczyyy/apollo-studio#2]
**Describe the bug**
It is stuck in the background and after i force close it with task manager and reopen it, nothing changes

**To Reproduce**

**Expected behavior**
I expected the app to open but after trying multiple times it never worked

**Screenshots**
If applicable, add screenshots to help explain your problem. https://cdn.discordapp.com/attachments/343522584652021760/512690242784985090/unknown.png

**Your setup**
Describe the system you are running on. Usually, just the OS is fine: 
Windows

**Additional context**

**Comment by Ev1ternity** [comment]
> What version of Windows are you running? I have a strong feeling it's not 10. Does a "api.exe" process exist in the background when you launch Apollo into the hanging state?

I'm using 10, i cant find an api.exe

**Comment by mat1jaczyyy** [comment]
https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.6-windows-hosting-bundle-installer try install this, restart and run again.

**Comment by Ev1ternity** [comment]
still doesn't work

**Comment by mat1jaczyyy** [comment]
what are the exact steps to reproduce from PC power-on? i will attempt to reproduce on a spare machine i have at home.

**Comment by Ev1ternity** [comment]
all's i do is turn on my pc, then turn the app on, and it get stuck

**Comment by mat1jaczyyy** [comment]
I was able to reproduce and I believe the cause is that no Launchpads are connected at the time of the app launching. Please try to connect a Launchpad before starting Apollo, let me know if this fixes your problem

**Comment by Ev1ternity** [comment]
got it to work

**Comment by mat1jaczyyy** [comment]
nice, so the issue is about 0 devices hanging.

**Comment by mat1jaczyyy** [comment]
An empty placeholder device is now created in this case. However, needs a proper fix. 999269d3ffda07db151e961a7f63425265cabac5

**Comment by mat1jaczyyy** [comment]
The new UI fully fixes this problem.
