### ISSUE TITLE
removing hex code in fade device makes apollo unresponsive

### ISSUE THREAD

**Issue by EjectUSB** [mat1jaczyyy/apollo-studio#20]
### Description
If you try to paste, remove or overwrite the hex code in the fade the entire program becomes unresponsive forcing you to quit the program and reboot it

### To Reproduce
Make new project
Open the track blablabla
Add the fade device
Select any point on the gradient
Select the hex code *AND THE "#" IN FRONT OF IT* and delete it/overwrite it by typing
_crash_

### Expected behavior
it not crashing

### Screenshots
Video: https://streamable.com/1ku4l

### Your setup
Windows 10, Launchpad MKII, Apollo build 9 up to commit 51255c504a5ce51b130d6dd8469c6cd3e85b5522

**Comment by mat1jaczyyy** [comment]
Fixed in c05b86f1962142bd328f8020ffbfc1e8a0f2ff25.
