### ISSUE TITLE
Color Picker for Pattern Editor

### ISSUE THREAD

**Issue by Ypsol** [mat1jaczyyy/apollo-studio#209]
Could you maybe add a color picker for finding the color of a light effect when you aren't the one who made it and want to use the same color or when you cleared your color history but want to continue using the same colors that were used until now in your project?

**Comment by mat1jaczyyy** [comment]
I believe this feature already exists, added as part of #27.

To pick a color off a currently existing Frame, you can hold Control while clicking the color you want. Is this the feature you're looking for?

**Comment by Ypsol** [comment]
Oh yes sorry i didn't know that worked.
