### ISSUE TITLE
Pattern Editor, sticky click&drag

### ISSUE THREAD

**Issue by M4kI9H7** [mat1jaczyyy/apollo-studio#22]
### Description
On Pattern editor, Click&Drag sticks, and just hovering over buttons will make buttons on/off.

### To Reproduce
 1. Click&Hold any buttons
 2. Drag the mouse out of buttons(to borders)
 3. Then release click
It can be un-stick by just clicking on a button.

### Expected behavior
No stuck click&drag on pattern editor

### Screenshots
none

### Your setup
apollo-9 win

**Comment by mat1jaczyyy** [comment]
Unlikely to be fixed soon, it's likely an issue with the Avalonia framework, but not sure.
