### ISSUE TITLE
Allow user to map a pad to the clear button

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#220]
### Is your feature request related to a problem? Please describe.
Kinda sick of creating a manual clear button that goes over all layers that I used in the project which I need to additionally remember before adding to the button.

### Describe the solution you'd like
Right-click clear button, LaunchpadGrid popup shows up and like with Pattern root keys you can select the button that clears the Launchpad. Right-click the selected pad to deselect and click anywhere outside the Launchpad to exit.

### Describe alternatives you've considered
Create a manual clear button that goes over all used layers. Can be a mess to figure out if you're doing spontaneous stuff.

**Comment by mat1jaczyyy** [comment]
How about this alternative: let's create a new Clear device, containing checkboxes for Multi Reset and Launchpad Clear. The Multi Reset would then be removed from the Switch device, and only available via the Clear device. Do you think this would satisfy your needs?

**Comment by rpgaleksy** [comment]
Sounds decent enough, yes.
