### ISSUE TITLE
BPM changes realtime

### ISSUE THREAD

**Issue by Ypsol** [mat1jaczyyy/apollo-studio#225]
### Is your feature request related to a problem? Please describe.
My question was:
"if the tempo of a song is automated can i also automate the light effects bpm in apollo?
can i for example make a light effect go faster and faster?"

### Describe the solution you'd like
A way to sync the tempo from ableton and apollo
OR
A way to automate tempo or color changes for a light effect over time or repetition

### Describe alternatives you've considered
variables in apollo? you could raise a variable everytime the effect is played which makes the tempo of the light effect faster every time but this would require more things to be added

### Your setup
yes

### Additional context
uwu

**Comment by mat1jaczyyy** [comment]
@Ypsol, is it enough that while an Ableton Connector is connected, we push BPM changes from Ableton to Apollo without affecting Undo history, and lock down the input text box on Apollo requiring the BPM to be set in Ableton?

**Comment by Ypsol** [comment]
You should definitely add that but i don't think that's enough because making an effect that is going faster and faster without a bpm change is very complicated at the moment. It would be nice to have something like an increase/decrease device as well so that you can map it to any parameter in other devices. It would increase the mapped parameter with each repetition of the light effect by the value you set in the increase device.

**Comment by mat1jaczyyy** [comment]
This is basically asking for automations, which I don't have the infrastructure for especially considering Undo/Redo history. See #169.

The idea was to change the BPM in Ableton via an arrangement automation, and then sync that value to Apollo. Potentially a M4L device could be used to trigger this change in Live? I think Nyrk created a device that does this, but even Twist could be modified for this purpose.

**Comment by Ypsol** [comment]
Alright then. Would be nice to have in Apollo but if it's too messy to implement, pushing BPM changes from Ableton should be fine too.
