### ISSUE TITLE
Mass select all frames in the pattern editor and then be able to change the length of all of them

### ISSUE THREAD

**Issue by EjectUSB** [mat1jaczyyy/apollo-studio#23]
### Is your feature request related to a problem? Please describe.
YES! When I have a spark of inspiration i want to make my light effect as fast as possible so i forget to change the length of the frames in the pattern window so when i'm done the light effect is super slow so....

### Describe the solution you'd like
It would be nice to have a way to mass select the frames and change the length of all of them

### Describe alternatives you've considered
i have no idea to be honest

**Comment by mat1jaczyyy** [comment]
Do you think a good implementation would be to hold Control while moving the Dial to make it apply to all frames?

**Comment by mat1jaczyyy** [comment]
Moved to #27.
