### ISSUE TITLE
When using copy and pressing buttons on the launchpad, the lights appear in the wrong places

### ISSUE THREAD

**Issue by busbob56** [mat1jaczyyy/apollo-studio#232]
### Description
Whenever a press a button when using the copy feature, it appears in the wrong place. When using the on-screen launchpad, it works fine.

### To Reproduce
After opening Track 1, click the plus sign and select copy. Press a button on the launchpad and the light appears in the wrong place. Open the on-screen launchpad and it works fine.

### Expected behavior
The lights are supposed to appear where the button is pressed.

### Your setup
WIN-Apollo 1.0

### Additional context
https://linksharing.samsungcloud.com/1564689523493CNNWonQ

**Comment by mat1jaczyyy** [comment]
You are likely using the wrong Input Format for your Launchpad. You can adjust this in the Launchpad Configuration page of the Preferences.

Launchpads utilize both the Drum Rack layout and the XY Layout. Depending on your mode, you'll want to use different layouts:

* MK2
   * Ableton Live closed - you need XY Layout
   * Ableton Live opened - you need Drum Rack layout
* Pro
   * Live mode
      * Ableton Live closed - you need XY Layout
      * Ableton Live opened - you need Drum Rack layout
   * Programmer mode - you need Drum Rack layout
   * Performance mode (custom firmware only) - your setting should match the layout setting in the setup of the Launchpad.

If you're not sure, try one then the other, one of these will always work.

**Comment by busbob56** [comment]
it worked, thank you
