### ISSUE TITLE
Playing light with Space button inside Pattern DEVICE.

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#243]
### Describe the solution you'd like
While in pattern DEVICE you could play light with the space button, something similar to ableton's light play functionality.

### Describe alternatives you've considered
Just add space functionality to pattern device.

**Comment by mat1jaczyyy** [comment]
Currently there's the Enter key. I picked it since it was closer to arrow keys and insert/delete. We'll expand to space as well.
