### ISSUE TITLE
Launchpad pattern preview is broken

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#244]
### Description
Sometimes when playing light effect on launchpad while in pattern device, launchpad froze and it needs a restart.

### To Reproduce
1. Go to pattern device.
2. "Spam" Play button in pattern device.
3. Done?

### Expected behavior
It needs to be fixed cause its annoying.

### Your setup
The same as always. Apollo 1.0.2

### Additional context
dms?

**Comment by mat1jaczyyy** [comment]
Fixed by a06d3d8.
