### ISSUE TITLE
Play Button w/sample in pattern

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#245]
### Is your feature request related to a problem? Please describe.
While im trying to do lights with long samples in sync, i need to exit pattern to play the light effect with samples.

### Describe the solution you'd like
Maybe add button that will play light effect and sample.

### Describe alternatives you've considered
Maybe also add this to space key. And if someone doesnt like it they can change it in preferences.

**Comment by mat1jaczyyy** [comment]
This is not easy to achieve... how does the Pattern know which sample it is, which key it should send to Ableton Live?

**Comment by Tuchan** [comment]
The same button that light effect is placed on + page.

**Comment by mat1jaczyyy** [comment]
"+ page"? I'm assuming you mean a KeyFilter before the Pattern. This has approach a couple issues:

* The KeyFilter might not have only 1 key mapped.
* The signal before the KeyFilter could have been processed and differs from the original input that should go to Live.
* The page inside of the Live project might mismatch, playing the wrong sample.

**Comment by mat1jaczyyy** [comment]
Closing because this is extremely impractical and near impossible to implement.
