### ISSUE TITLE
An indicator on the selected or played chain

### ISSUE THREAD

**Issue by whysofast** [mat1jaczyyy/apollo-studio#256]
### Is your feature request related to a problem? Please describe.
I got to search in chains one by one to find the effect that I want to copy or access to make an modification.

### Describe the solution you'd like
An indicator on the selected or played chain, which in the second case, just when enabled(like on ableton)

### Your setup
Win10 , Apollo 1.0.7

**Comment by mat1jaczyyy** [comment]
Duplicate of #106. If an issue is closed with wontfix, don't feel bad to comment on it expressing why you think we should still have it :)
