### ISSUE TITLE
Can't use Apollo with Ableton

### ISSUE THREAD

**Issue by NameP01NTER** [mat1jaczyyy/apollo-studio#257]
### Describe your inquiry
I want to use Ableton Live 9 Standard alongside apollo studio to create Launchpad Cover, but although Ableton recognizes the Launchpad, it's input and output are marked orange and I can't use the launchpad in Ableton Live, only in Apollo.

### Your setup
Launchpad MK2
Ableton Live 9 Standard

### Additional context

![image](https://user-images.githubusercontent.com/48490913/63954674-bf44e280-ca83-11e9-8bed-bd707955783b.png)

**Comment by mat1jaczyyy** [comment]
Assuming this is Windows.

Are you able to run Apollo alone without Ableton? This issue is most often caused by lacking Novation's USB driver which Apollo will refuse to start without. Can you check who the manufacturer of your Launchpad is in the Properties window of its' entry in the Device Manager?

**Comment by NameP01NTER** [comment]
Thank you for the quick reply, and sorry for not detailing my problem enough.
Yes, I'm on Windows 10 (64bit).
I'm able to run both pieces of software (Ableton and Apollo) individually without any issue, but as soon as I start using them together, one of them doesn't work with the Launchpad anymore. 

When I start Apollo before Ableton, it works perfectly, but Ableton doesn't (it shows the orange input and output, see above picture).
When I start Ableton first, it also works with the Launchpad, but Apollo simply does not recognize the Launchpad (it doesn't show it in the preferences).

The Device Manager says that my Launchpad MK2 is manufactured by Microsoft? What? (See screenshot)

![image](https://user-images.githubusercontent.com/48490913/63967320-7732b980-ca9d-11e9-90bc-0adc3f72121a.png)

Hope this helps, I can supply more information if needed.

**Comment by mat1jaczyyy** [comment]
You're checking under Software devices. Please check under Sound, video and game controllers. My guess is you have the required driver installed, but your Launchpad isn't configured to use it.

**Comment by NameP01NTER** [comment]
Sorry, here's a screenshot from Sound, Video and game controllers.
![image](https://user-images.githubusercontent.com/48490913/63974199-a69cf280-caac-11e9-8b3c-c2b207f56097.png)

I have two Launchpad MK2's and both of them share the same Properties.

**Comment by mat1jaczyyy** [comment]
Yeah, they're not using the driver. Your best bet is to try reinstall it while the Launchpads are plugged in, it should apply properly. Novation made it hard to find it on their website, it's listed under just 'Launchpad' on their download pages. Alternatively, Apollo's installer installs the driver for you during the installation.

**Comment by mat1jaczyyy** [comment]
The manufacturer should say Focusrite when the driver is loaded properly.

**Comment by NameP01NTER** [comment]
I'll try that tomorrow, thank you for your help.

**Comment by NameP01NTER** [comment]
I fixed the issue. 
Sadly, reinstalling Apollo or the Novation Driver with the Launchpads didn't do the trick, but I found another, easier way.

Open device manager, right click your Launchpad under Sound, video and game controllers and press "Update driver" > "Browse my computer for driver software" > "Let me pick...".
Then you need to uncheck "Show compatible devices" which then allows you to select the "Focusrite Audio Engineering, Ltd." Manufacturer. After that you can simply select the latest driver for your launchpad, but don't select the wrong one because it will cause a BSOD. Press "Next" and "Yes".

Restart your computer and it should all work.

**Comment by mat1jaczyyy** [comment]
Yeah, just Novation weird stuff... not their only issue with their software. Glad you got it resolved.
