### ISSUE TITLE
Fade: Smoothing options

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#267]
Wouldn't technically call this an `enhancement` but okay

**Comment by SimplyMerlin** [comment]
Reference GIF: https://i.imgur.com/5WpV4t4.gif

**Comment by mat1jaczyyy** [comment]
Ok what if I implemented all of those in the gif

**Comment by TheLifeGamingYT** [comment]
Well you can make a dial not just options I think.

**Comment by mat1jaczyyy** [comment]
Dials aren't nice for multiple choice options though.

**Comment by TheLifeGamingYT** [comment]
For dials, I meant to not have multiple options, a potentiometer from 0% to 100% like the Fade Smoothness in Preferences.

Da: mat1jaczyyy
Inviato: lunedì 21 ottobre 2019 15:14
A: mat1jaczyyy/apollo-studio
Cc: Andrea Giurgola; Comment
Oggetto: Re: [mat1jaczyyy/apollo-studio] Fade: Smoothing options (#267)

Dials aren't nice for multiple choice options though.

**Comment by mat1jaczyyy** [comment]
That's a separate issue of sorts, this issue is talking about different smoothing settings, ie the curve of the smoothness, not the precision. The precision is meant for people for lower-end specs to be able to have less precision in their fades which enables them to play projects without lag.

**Comment by TheLifeGamingYT** [comment]
That's what I meant. Maybe I explained it wrong. You can use a dial, or you can make it more graphical, using an actual curve.

**Comment by mat1jaczyyy** [comment]
Why is implements not an issue closing keyword? Closed by #297.
