### ISSUE TITLE
Offsetting

### ISSUE THREAD

**Issue by ARandomOneTTV** [mat1jaczyyy/apollo-studio#268]
### Description
Before I open an Ableton project, everything is OK, but whenever I open an Ableton project the buttons are offset, I don't know if this is a bug with the Ableton Project or with Apollo.

### To Reproduce
I open the Apollo Project, then I press some buttons to make sure everything is OK, then I open the Ableton project, change the MIDI stuff on Ableton because the project is for launchpad pro (I have MK2), press some buttons and it's suddenly offset

### Expected behavior
I expected the buttons to be in the right place, obviously

### Your setup
OS: Microsoft Windows 10 Pro
Apollo Version: 1.1.0 (i think)

### Additional context
My phone is sadly dead but would take some pictures or videos

**Comment by mat1jaczyyy** [comment]
Looks like a duplicate of #232. The Launchpad supports two layouts, one is mainly used without Ableton while the other is mainly used with Ableton. See if [this comment](https://github.com/mat1jaczyyy/apollo-studio/issues/232#issuecomment-517442753) can help you.

**Comment by ARandomOneTTV** [comment]
Yes! It worked! Thank you *SO* much!

wt., 24 wrz 2019 o 19:59 mat1jaczyyy <notifications@github.com> napisał(a):

**Comment by mat1jaczyyy** [comment]
Glad to resolve the problem!
