### ISSUE TITLE
Pattern editor improvements

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#27]
- [x] Map gestures to numpad
- [x] Mass Duration change
- [x] Color pick tool
- [x] Mono/Poly/Loop playback toggle
- [x] Choke groups
- [x] Play/Fire buffered engine

**Comment by rpgaleksy** [comment]
Also, maybe an option to choose the zoom level & position of a gif when loading it into Pattern.

**Comment by mat1jaczyyy** [comment]
isn't that what image editors are for? let's not reinvent the wheel

**Comment by rpgaleksy** [comment]
Referencing #23 I think the Ctrl+Drag thingy might be a good secondary option, mass-selection can still be applied to just chunks too while Ctrl just does it for everything.

**Comment by mat1jaczyyy** [comment]
Map gestures to numpad solved with 2bc0a09.

**Comment by mat1jaczyyy** [comment]
Mass Duration changesolved with dcf8ed3.

**Comment by mat1jaczyyy** [comment]
Color pick tool solved with cd8248c.

**Comment by mat1jaczyyy** [comment]
Mono/Poly/Loop solved with fed2814.

**Comment by mat1jaczyyy** [comment]
Choke groups solved with 622b3b3.

**Comment by mat1jaczyyy** [comment]
Play/Fire buffered engine solved with 9ef381b.
