### ISSUE TITLE
Type precise values

### ISSUE THREAD

**Issue by TheLifeGamingYT** [mat1jaczyyy/apollo-studio#28]
### Is your feature request related to a problem? Please describe.
Yes, it is. Because in the Pattern device, when I use the Duration dial to assign to it the value 200ms, it can be 197ms or 210ms, but not 200ms. Also because it makes a lot faster the process of making.

### Describe the solution you'd like
Like in Ableton, when you click on a dial, slider, etc., you can type in the precise value.

### Describe alternatives you've considered
what do you mean by that

### Additional context
FL Studio is love, FL Studio is life.

**Comment by Niekxd** [comment]
You aren't supposed to be using Apollo, let alone giving feedback on it. Like mat said, there are already enough testers.
