### ISSUE TITLE
Can't write values to non-hidden TextBoxes

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#282]
### Description
Writing in textboxes in Fade or Color does not work.

### To Reproduce
Open Apollo, create project and add Color or Fade device. Try changing the color value by typing.

### Expected behavior
Typable value.

### Your setup
Windows 10 Build 1803
Apollo 1.1.2

**Comment by mat1jaczyyy** [comment]
Only ColorPicker is broke.

**Comment by mat1jaczyyy** [comment]
BPM TextBox also broke.

**Comment by mat1jaczyyy** [comment]
Author TextBox also broke.

**Comment by mat1jaczyyy** [comment]
Fixed by 8c11ef5.
