### ISSUE TITLE
Choke doesn't send Stop signal to inner Chain

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#283]
### Description
Pressing the "Clean Launchpad" icon does not stop lightshows before clearing, resulting in ongoing lightshows continuing until they end.

### To Reproduce
Play a really long repetitive Lightshow like in Fireflies, press the brush icon.

### Expected behavior
Lightshows stop and are then cleared.

### Your setup
Windows 10 1803
Apollo 1.1.2

## Additional context
https://drive.google.com/open?id=1CIJeA5AtxO9hgAXtTyUrCzeSVu0Clht4
Example .approj

**Comment by mat1jaczyyy** [comment]
Can you provide a consistent .approj for repro?

**Comment by rpgaleksy** [comment]
Updated post with link to offending .approj
