### ISSUE TITLE
Apollo has no output after PCs screensaver turns on

### ISSUE THREAD

**Issue by TheMarkTwo** [mat1jaczyyy/apollo-studio#284]
### Description
Apollo has no output after PCs screensaver turns on

### To Reproduce
Let pc go into screensaver mode

### Expected behavior
not lose output

### Your setup
windows 10 pro apollo 1.1.2

**Comment by mat1jaczyyy** [comment]
This is due to some Windows stuff turning off USB devices when your computer enters sleep mode I guess.  The MIDI library reports the port is there but refuses to send messages to it, so not much I can do anyway...
