### ISSUE TITLE
Mode light can't be moved by Move or Copy device

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#286]
### Description
When using a Move or Copy device, the mode light is not affected by positional changes made in either device.

### To Reproduce
Create signal on Mode light and attempt to move or copy it to a different place.

### Expected behavior
Mode light being moved/copied to a different place on the Launchpad.

### Your setup
Windows 10 1803
Apollo 1.2.0 c7092db

### Additional context
https://drive.google.com/open?id=1URj6JYKboDU1blK6J_-U9tPIwhRqhPZl

**Comment by mat1jaczyyy** [comment]
Intended behavior.
