### ISSUE TITLE
Mode light does not display on Launchpad

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#287]
### Description
See title, it gets displayed on the Preview and Virtual Launchpad but not on the actual device.

### To Reproduce
Create Pattern with Mode light on. Trigger the pattern.

### Expected behavior
Mode light being lit on the Launchpad.

### Your setup
Windows 10 1803
Apollo 1.2.0 c7092db

### Additional context
https://drive.google.com/open?id=1njJC74YmuU6iOivnk5_RR-xJmS-0LqPK

**Comment by rpgaleksy** [comment]
Update: Only occurs on launchpad-x branch with given commit number.

**Comment by mat1jaczyyy** [comment]
Fixed on branch with effbade.
