### ISSUE TITLE
Hold doesn't hold light effects in some situations

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#288]
### Description
In some situations, a light effect that is supposed to be held infinitely after it is finished does not hold and just disappears as if there was no hold placed.

### To Reproduce
Use provided .approj

### Expected behavior
Behaviour like in Apollo v1.1.2, where the light effect is being held forever.

### Your setup
Windows 10 1803
Apollo 1.2.0 c7092db

### Additional context
https://drive.google.com/open?id=1daWMHZ2YuzyWclV7qwb6AaQAIg0yvn9x

**Comment by mat1jaczyyy** [comment]
Fixed on branch by e58d8c5.
