### ISSUE TITLE
Closing minimized windows softlocks newly created windows

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#292]
### Description
When closing minimized Apollo windows that open a "root" window (Track -> Project. Project -> splash screen) using the Windows taskbar hover-preview, the "root" window will refuse to unminimize itself, requiring to restart Apollo.

### To Reproduce
Open Apollo and a window that is not the splash screen.
Minimize the window and close this window using the Windows hover-preview.
Attempt reopening the newly created, minimized window.

### Expected behavior
Normal un-/minimize behavior throughout.

### Your setup
Windows 10 1803
Apollo 1.2.0 Prerelease 2

**Comment by mat1jaczyyy** [comment]
Reproduced. As a temporary workaround for earlier versions, you can open the Task Manager and maximize Apollo's softlocked window.
