### ISSUE TITLE
Memory leaks everywhere

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#293]
### Description
A similar issue happened in an earlier version when reopening existing chains.
Reopening and closing pattern windows with a non-trivial amount of frames doesn't seem do deallocate memory when closing them correctly, resulting in more memory needed over time.

### To Reproduce
Open the attached file and open/close/reopen the contained patterns a couple of times.

### Expected behavior
Correct deallocation of memory.

### Your setup
Windows 10 1803
Apollo Studio 1.2.0

### Additional context
![patterndeallocate](https://user-images.githubusercontent.com/38407233/68369434-981d2800-013a-11ea-850b-2789aa2bafac.png)

[patternDeallocate.zip](https://github.com/mat1jaczyyy/apollo-studio/files/3818394/patternDeallocate.zip)

**Comment by Brendonovich** [comment]
After doing some testing, it seems that this issue occurs when opening and closing the Track and Project windows, maybe there's a memory leak within Avalonia?
<img width="327" alt="after" src="https://user-images.githubusercontent.com/14191578/68760687-68e04c80-064d-11ea-9609-c7095c76f475.png">
<img width="329" alt="before" src="https://user-images.githubusercontent.com/14191578/68760688-68e04c80-064d-11ea-92c9-408f17895ea6.png">

**Comment by mat1jaczyyy** [comment]
This seems to happen with all custom elements on all windows. I've improved the memory on LaunchpadGrid (the heaviest component) slightly, but it still causes a 2MB leak per created instance. Dials from devices and LaunchpadGrids are the most affected. This looks like an Avalonia issue to me too.

**Comment by mat1jaczyyy** [comment]
@rpgaleksy Willing to backtrace if there's a version of Apollo where this doesn't happen?

**Comment by mat1jaczyyy** [comment]
Consistent repro: make 20 delays in a Track, and then close/reopen the Track window.

**Comment by mat1jaczyyy** [comment]
Pretty sure this is just an Avalonia thing. https://github.com/AvaloniaUI/Avalonia/issues/3269 Waiting on this

**Comment by mat1jaczyyy** [comment]
Avalonia seems to have fixed this, so we can include this in 1.3.0

**Comment by mat1jaczyyy** [comment]
Fixed with https://github.com/AvaloniaUI/Avalonia/pull/3331
