### ISSUE TITLE
LPX/MiniMk3: Fade interpolates #010101 to #000000

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#295]
### Description
Noticed when attempting to use Hold (inf) the last color of a Bright-to-Black Fade.
#010101 is being interpolated to #000000 resulting in the Hold (inf) not holding correctly.
Works correctly on colors that are #010000, #010100 or equivalent examples as well as #020202 and above though.

Only occurs on the X and Mini Mk3!

### To Reproduce
Create Fade going from any color to #010101.
Place Hold (infinite) after the Fade and trigger a Fade.

### Expected behavior
Correct interpolation and holding behaviour.

### Your setup
Windows 10 1803
Apollo Studio 1.2.0

**Comment by mat1jaczyyy** [comment]
Thanks Novation

**Comment by mat1jaczyyy** [comment]
What really happens here is that Novation take a value from 0 to 127 on the new Launchpads for RGB, leading me to think the color is 7-bit per channel. In reality, the color is still 6-bit, and the 6 higher bits of the 7-bit value are used, causing #010101 to match #000000 but also #030303 to match #020202. We'll likely revert Apollo Studio back to 6-bit color to address this issue.
