### ISSUE TITLE
Exporting audio - Apollo Connector Bug

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#296]
### Description
While exporting audio (aka tutorial) using apollo connector, it seems that ableton is triggering buttons presses and that leads to apollo being triggered which leads to whole bunch of light effects playing at once.

### To Reproduce
Record tutorial (need lights), export audio.

### Expected behavior
It should stop playing the whole project in 2 seconds lmao

**Comment by rpgaleksy** [comment]
If there is an observable property in the Live API that allows checking for the rendering/exporting process, this should be an easy fix. I'm going to look for something like that.

Disable the connector plugin or put an empty Key Filter in front of your chain while exporting as a workaround if it really bothers you.

**Comment by mat1jaczyyy** [comment]
Well, I can't find anything like this in the Live API. Not sure what to do about this, but I'm thinking about it.

**Comment by mat1jaczyyy** [comment]
Didn't quite fully fix it, but as of 75539b0 Apollo Connector has a Mute toggle you can use to disable sending inputs to Apollo temporarily.
