### ISSUE TITLE
Bluescreen on Disconnect

### ISSUE THREAD

**Issue by ThreeStarLaunchpad** [mat1jaczyyy/apollo-studio#30]
### Description
When using 2 CFW Launchpads, disconnecting one of them gives a bluescreen

### To Reproduce

Disconnecting your 2nd Launchpad while using Apolllo lol

**Comment by EjectUSB** [comment]
Hey! Could you please edit this issue so that it fully follows the issue template as seen in here? https://github.com/mat1jaczyyy/apollo-studio/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mat1jaczyyy** [comment]
No need. Can you provide a crash dump from Windows? should be inside C:\Windows\Minidump if I'm not mistaken

**Comment by ThreeStarLaunchpad** [comment]
There is nothing in that folder

**Comment by mat1jaczyyy** [comment]
@ThreeStarLaunchpad what is the exception received at the blue screen?

**Comment by mat1jaczyyy** [comment]
Assuming user-specific error and closing.
