### ISSUE TITLE
Choke Devices from Context Menu

### ISSUE THREAD

**Issue by TheMarkTwo** [mat1jaczyyy/apollo-studio#300]
### Is your feature request related to a problem? Please describe.
Feature: Whilst having selected multiple devices in a chain, add the ability to add them to a choke group directly from the context menu (drop down menu)

### Describe the solution you'd like
add this option

### Your setup
Win10 #299

**Comment by mat1jaczyyy** [comment]
ok

**Comment by TheMarkTwo** [comment]
Also make it so that when you right click the choke device, unchoke it

**Comment by mat1jaczyyy** [comment]
ok
