### ISSUE TITLE
Switch: Macro Ramping

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#317]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
Have Switch devices be able to ramp up a macro like Twist can in Live.

### Describe alternatives you've considered
A lot of timed switches, very unpractical.

### Your setup
Apollo 1.3.0 PreRelease 3

**Comment by mat1jaczyyy** [comment]
actual use case for this pls

**Comment by mat1jaczyyy** [comment]
yeah so i can't really find a use case, the mentioning issues are also asking for things which don't really make sense, i think this is safe to close until a concrete example shows up.
