### ISSUE TITLE
invalid .mid/.gif causes c r a s h

### ISSUE THREAD

**Issue by EjectUSB** [mat1jaczyyy/apollo-studio#32]
### Description
if you import a broken midi/gif file the program will crash

### To Reproduce
1. get a random file
2. rename it to .mid/.gif
3. try to import it

### Expected behavior
error message

### Screenshots
_bro it's 12pm why do you force me to actually make this bug report_

### Your setup
windows 10 apollo 10

### Additional context
i want sleep kbye

**Comment by mat1jaczyyy** [comment]
Error message is currently not trivial to implement, due to Avalonia not yet supporting MessageBoxes. However, the crash no longer occurs.
