### ISSUE TITLE
Fade: Resize gradient area

### ISSUE THREAD

**Issue by Hitacium** [mat1jaczyyy/apollo-studio#320]
### Is your feature request related to a problem? Please describe.

Not really !

### Describe the solution you'd like

Just make a little zoom tool on the bottomed of track window ! For zoom all devices

### Describe alternatives you've considered

If you can't ! Make a zoom of keys of fade.

### Your setup

window 10
Apollo 1.3.0

**Comment by mat1jaczyyy** [comment]
Not really possible or useful in any way to zoom entire Track window, apart from OS DPI settings. Though resizable Fade should be a possibility.

**Comment by mat1jaczyyy** [comment]
This can be done by dragging the Border between the Gradient and ColorPicker, initiating a resize action.
