### ISSUE TITLE
Multi: Key mode

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#322]
### Is your feature request related to a problem? Please describe.
Only a slight inconvenience.
Making an effect that for example has the same shape across all buttons but changes color depending on which of those buttons gets pressed can't be made without using duplicates of the same pre-processing device in multiple chains within a group.

### Describe the solution you'd like
A "Key" mode in Multi that assigns each Multi chain a preprocessing-Keyfilter for key-mappable post-process effects.

### Describe alternatives you've considered
Using a group with Keyfilters and multiple duplicates of the exact same shaping device (e.g. Copy) with different colors to post-process.

### Your setup
Apollo 1.3.0
Windows 10 1903

### Additional context
![multikey](https://user-images.githubusercontent.com/38407233/70745256-b2db5180-1d23-11ea-8e39-9b5e279e3f3b.png)

**Comment by rpgaleksy** [comment]
I'll take a look at whether I can implement this myself.

**Comment by mat1jaczyyy** [comment]
Closed by #324.
