### ISSUE TITLE
Add RGB to ColorPicker

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#327]
### Is your feature request related to a problem? Please describe.
I can't remember the HEX numbers for my necessary colors, but I know perfectly all the RGB mixes.

### Describe the solution you'd like
What do you think about adding a switch to select HEX or RGB (0-255) ? So you can input both, just clicking the switch?

### Describe alternatives you've considered
I used a converter online to know my HEX values I needed

### Your setup
Windows 10
Apollo 1.3.1

**Comment by mat1jaczyyy** [comment]
Would it be okay to have the RGB values range from 0 to 63 as they are on the actual Launchpad? You'd still have to divide your colors by 4. The hex also ranges 0-3F (consistency), and the Launchpad works with that range of values so it doesn't make sense to use 8-bit screen color for this.

**Comment by mat1jaczyyy** [comment]
@Brendonovich sounds like an easy one for you to add in the preferences

**Comment by Brendonovich** [comment]
You could have a toggle button next to the text box that switches between hex and rgb, I'll work on it soon

**Comment by mat1jaczyyy** [comment]
I don't think there's room for a temporary toggle, my thought was this would go into the Preferences. I get sometimes you want to switch often, but how do you handle the default setting when there are multiple pickers on screen?

**Comment by Brendonovich** [comment]
Fair enough, I'll put something in preferences

**Comment by mat1jaczyyy** [comment]
Closed by #330.
