### ISSUE TITLE
Refresh device

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#328]
### Is your feature request related to a problem? Please describe.
Yes. Dynamic* lightshows are not possible due to the properties of Signals not being able to change while traversing the contents of a track.
These properties are set only once in their "lifetime" when leaving the hardware.

### Describe the solution you'd like
A Refresh device that lets users refresh/reset(?) selectable properties of passing Signals
(**at users own risk** since it definitely can cause crashes in specific situations e.g. refreshing Multi target within Multi preprocessing chain).

### Describe alternatives you've considered
No feasible alternatives were found yet that aren't more complicated and/or confusing.

### Your setup
Apollo 1.3.1
Windows 10 1903

### Additional context
*Dynamic lightshows, meaning a light effect that looks a certain way on its own, but changes its shape for instance, once a specific second light effect is triggered.
Example: Horizontal line moving from right to left splitting into two seperate lines once the bottom-corner pad is pressed.
[DynamicLightshowsUsingMacros.zip](https://github.com/mat1jaczyyy/apollo-studio/files/4000031/DynamicLightshowsUsingMacros.zip)

**Comment by mat1jaczyyy** [comment]
The only thing that is "kept as was when the Signal was spawned" is the Macro state, I guess a refresh device for this purpose only would be ok

**Comment by mat1jaczyyy** [comment]
What do we put in the UI for this lmao

@rpgaleksy I guess sometimes we want to refresh some macros but not all macros, add 4 checkboxes for each macro?

**Comment by rpgaleksy** [comment]
Good call actually, sounds more than doable.

**Comment by mat1jaczyyy** [comment]
This hinders future optimizations, like those which could solve #138. Considering reverting and thinking of an alternative solution for this.

**Comment by mat1jaczyyy** [comment]
Remerging this to 1.5.0

**Comment by mat1jaczyyy** [comment]
Merged to master #348
