### ISSUE TITLE
Drag and drop devices

### ISSUE THREAD

**Issue by Niekxd** [mat1jaczyyy/apollo-studio#331]
I think this will make the workflow a bit easier for me personally because it is more visible and easier to work with. Maybe add a favorites system as well, where the devices you favorite are the first on the list, and maybe like a small option where you just have the device names without the descriptions. (see image)

![image](https://user-images.githubusercontent.com/29899069/71556840-802c9b00-2a3d-11ea-9df2-f0b047ed6ba2.png)
![image](https://user-images.githubusercontent.com/29899069/71556862-d6014300-2a3d-11ea-80cc-2925fffe92a8.png)

**Comment by Consoli0** [comment]
Sounds nice, would add to the visual space apollo takes, but still sounds nice, I also in general see Apollo Studio is just kinda slow

**Comment by mat1jaczyyy** [comment]
I don't like this idea because I feel it takes up too much space, and Apollo is designed to be over Ableton's window. The list of devices is already well organized and non-intrusive. If I wanted it to be large and normal I'd have a regular large window instead of the window-based workspace.
