### ISSUE TITLE
Drag'n'Drop: Improved visual responses when only clicking

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#338]
### Description
Nothing major, just something visual that affects how dragging and dropping feels.
For example, clicking onto a Track in the Project window, a rectangle appears beside the cursor.
IMO it would look/feel better if the rectangle only appeared once the mouse with a held button is moved by a bit.
Similar behavior for Track contents (cursor turns into a "forbidden" sign).

### To Reproduce
Click almost any drag'n'drop-able (content) element in the Project or Track window.

### Expected behavior
Changed cursor icon only upon movement, not upon click.

### Your setup
Apollo 1.3.3
Windows 10 1903

**Comment by mat1jaczyyy** [comment]
This is too odd to work around, Avalonia's drag and drop support is fuzzy anyways, and this really bothers no one.
