### ISSUE TITLE
Midi Exporting

### ISSUE THREAD

**Issue by LaunchpadPhil** [mat1jaczyyy/apollo-studio#339]
Adds the function to export as ".mid" via the export button

**Comment by TheLifeGamingYT** [comment]
I don't think you can export SysEx messages in a MIDI file. If you use Apollo, why don't just use it with Ableton, rather than using it just as a MIDI file generator.

**Comment by TheLifeGamingYT** [comment]
I would already close this.

**Comment by Guest173661** [comment]
Plus, It wouldn't be possible:
![Screenshot_20200112-233219](https://user-images.githubusercontent.com/29669519/72221259-e6640280-3593-11ea-9038-095dfeba701f.jpg)

**Comment by LaunchpadPhil** [comment]
ok forgot about this I'm going to close this
