### ISSUE TITLE
Fade Smoothness skips over Color when there is no Color close to it

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#342]
### Description
"_[...] why color bad reeeeeeeeeeeeeeeeeeee_"
ahem.. creating a single-color Fade with more than one thumb can result in weird behavior of the color that is being interpolated to last. This usually manifests in the last color being held on for too long (until end of the Fades rate I believe).

### To Reproduce
Use the attached device code to trigger a fade.

### Expected behavior
Behavior like in a Fade device with half the length and only the beginning and end thumbs.

### Your setup
Apollo 1.3.3
Windows 10 1903

### Additional context
QVBPTBsAAAABAQAAAAUAAQodARsGAAAA6AMAAAAAAAAAAPA/AAAAAAMAAAAZPwAAGQAAABkAAAAAAAAAAAAAAAAAAAAAAOA/AAAAAAAA8D8AAAAABQAAAAEAAAAA

**Comment by mat1jaczyyy** [comment]
30% smoothness exact to repro this
