### ISSUE TITLE
Pattern import broken

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#35]
### Description
Apollo crashes when importing valid .gif/.mid files into Pattern device.

### To Reproduce
Create Pattern device and import GIF or MIDI file.

### Expected behavior
No crash.

### Screenshots
-

### Your setup
Win 10 (1803)
Apollo 10 9b9b9be

### Additional context
Error Code:
Exception has occurred: CLR/System.ArgumentOutOfRangeException
Eine Ausnahme vom Typ "System.ArgumentOutOfRangeException" ist in System.Private.CoreLib.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.: 'Index was out of range. Must be non-negative and less than the size of the collection.'
   bei System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   bei Avalonia.Collections.AvaloniaList`1.get_Item(Int32 index)
   bei Apollo.Windows.PatternWindow.Frame_Select(Int32 index) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Windows\PatternWindow.cs: Zeile245
   bei Apollo.Windows.PatternWindow.ImportFile(String path) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Windows\PatternWindow.cs: Zeile498
   bei Apollo.Windows.PatternWindow.<ImportDialog>d__61.MoveNext() in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Windows\PatternWindow.cs: Zeile531

**Comment by EjectUSB** [comment]
Duplicate of #32.

**Comment by EjectUSB** [comment]
nvm im stupid pls ignore thancc

**Comment by mat1jaczyyy** [comment]
@rpgaleksy is this an issue on Build 10 from Releases?

**Comment by rpgaleksy** [comment]
Reproable on latest commit you did, Build 10 itself still works fine.
