### ISSUE TITLE
Multi: Drag'n'Drop of chain in Multi key mode behaves inconsistently

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#351]
### Description
See title.

### To Reproduce
Create Multi and at least one chain in key mode. Draw something in. Create a second Multi and drag the existing chain in there. The Keyfilter will be empty as well as not recoverable by undoing the action.

### Expected behavior
Normal drag'n'drop as well as undo/redo behavior.

### Your setup
Apollo 1.4.0
Windows 10 1903

**Comment by mat1jaczyyy** [comment]
Woops this is also a thing with Operations (copy/paste etc) wondering if I should just make this a part of Chain secretly
