### ISSUE TITLE
Group: Allow importing Devices

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#357]
Would create a new chain for these

**Comment by Brendonovich** [comment]
What does this mean

**Comment by mat1jaczyyy** [comment]
Just like how you can drag Devices into a Chain directly, you should also be able to import .apdev on a Chain directly

**Comment by mat1jaczyyy** [comment]
Eh this is a pain in the ass and doubt this feature is wanted so much, easy to do yourself just make a chain and import your device
