### ISSUE TITLE
Auto Mode Light

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#365]
### Is your feature request related to a problem? Please describe.
I sometimes just forget about mode light.

### Describe the solution you'd like
Maybe we could get a tick box or just a device for automatic mode light whenever the lights on "solo" and "volume" buttons are on. It would just copy those lights and paste them onto mode light.

**Comment by mat1jaczyyy** [comment]
I mean, you can add a Group with a Chain with KeyFilter for regular keys to pass through and a 2nd Chain with KeyFilter for Solo/Volume which you can Static Copy down to the Mode Light? It does exactly what a new Device would do

**Comment by mat1jaczyyy** [comment]
Solved.
