### ISSUE TITLE
LaunchpadType Filter

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#374]
### Is your feature request related to a problem? Please describe.
No, just a new feature to be introduced

### Describe the solution you'd like
I would like a new device called the **launchpad filter** or at least something similar to be in apollo, a device that will only allow messages to pass if the launchpad is the one that is selected in the device. For example, if I want the drum lights to be different depending on the launchpad, I can put different variations of the drum lights in a group, but each one is triggered if a corresponding launchpad is connected. So the light will be different for each launchpad, for example.

### Your setup
I run Windows 10 with Apollo 1.5.0

### Additional context
Can it be introduced in apollo 1.6 maybe?
Thank you!

**Comment by LaunchpadPhil** [comment]
That'd be nice to have

**Comment by rpgaleksy** [comment]
Sounds interesting, can you give a particular use case that can't be realized with the currently given functionality/devices? @YarostheLaunchpadder

**Comment by YarostheLaunchpadder** [comment]
@rpgaleksy I gave an example with drum lights in my request, but here is another one, for example, if I  want my effect to display something with the mode light if a pro is connected, or display on novation logo when connected a launchpad X or higher. You put both of the effects in the page group, but only one is triggered at a time because only one launchpad is triggering the effect, so the device will do this:

you select the launchpad you want in the device and it only passes the note-on signal if the launchpad that is triggering the note is the one selected. I think it will be useful in some cases.

**Comment by Brendonovich** [comment]
@YarostheLaunchpadder Do you mean have separate effects on the mode light and the novation light? Apollo handles the location of the two depending on which Launchpad you are using, so I don't see how this would help. Please correct me if I'm misunderstanding

**Comment by YarostheLaunchpadder** [comment]
No, I mean a device that will allow different effects depending on the launchpad connected, so maybe if it´s an mk2 a certain effect will be different shape or color than pro or X. Do you understand now? You can read my initial message/request to understand a little bit more.

**Comment by Brendonovich** [comment]
I mean it can be done but I don't see a whole lot of utility for it. Why would you want to change an effect's color/shape for different Launchpads? Ultimately up to @mat1jaczyyy to decide if it makes it in

**Comment by YarostheLaunchpadder** [comment]
@Brendonovich, For example, drum lights do not look that nice when you change launchpads, but yeah, I totally agreed that mat1 decides, and let's see if he adds it.

**Comment by rpgaleksy** [comment]
I think I understood correctly now.

Variable lightshows depending on what Launchpad model is connected, not necessarily within a multi-track arrangement.
Assuming only one track, connecting a Pro would display "Lightshow variation X", disconnecting it, and connecting an X to the same track could display "Lightshow variation Y" on the same key/page.. right? @YarostheLaunchpadder 

In this case, the idea would be a "nice/fun to have", not much more (in my opinion).

**Comment by YarostheLaunchpadder** [comment]
@rpgaleksy Exactly! This is what I meant.

**Comment by mat1jaczyyy** [comment]
I understand this isn't implemented but I'm failing to see how this can create any meaningful changes to effects. Apollo already considers top row positioning automatically, and the mode/novation LEDs are mutually exclusive (differently positioned from one another and can be controlled individually). You can make effects which send to both, and they'll display only on hardware that supports displaying them.

This kind of goes against Apollo's philosophy of generalizing everything to make it as straightforward as possible, working seamlessly with all kinds of LPs.

**Comment by rpgaleksy** [comment]
I might still take a look at implementing this (even if it just ends up being practice..).
The number of sensible use cases appears to be even smaller than those for the Refresh device so I don't see much success in it ending up in an official version of Apollo.

**Comment by mat1jaczyyy** [comment]
Won't be implementing this, sorry.
