### ISSUE TITLE
Rename Devices

### ISSUE THREAD

**Issue by nyrkmusic** [mat1jaczyyy/apollo-studio#375]
### Is your feature request related to a problem? Please describe.
It's hard to keep track of all the devices (especially groups) when you can't rename them like "pages, filter, colors" etc.

### Describe the solution you'd like
The best solution to this would be if you were able to just right click on a device (not a chain) and get the rename option just like you do for the chains.

### Describe alternatives you've considered
While not nearly as minimal and perhaps practical, being able to assign colors to device might be something others would like to do to keep them organized.

### Your setup
I'm using Apollo Studio 1.6.2 on MacOS 10.15.5

### Additional context
Creating all my samples in Ableton Live I was already used to this option and was therefore wondering why it's not implemented yet.

**Comment by mat1jaczyyy** [comment]
#146

**Comment by mat1jaczyyy** [comment]
Duplicate
