### ISSUE TITLE
Some effects freezing when playing multiple simultameous effects

### ISSUE THREAD

**Issue by D3RPSTROYER** [mat1jaczyyy/apollo-studio#376]
Version: 1.6.2
launchpad: Launchpad MK2

I have a rainbow effect playing on the main 8x8 board on a launchpad MK2 which is played by running a plain white pattern into a fade effect to make it rainbow. I also have a plain pattern along the top and sides running into a fade to fade from white to black.

individually they're fine, however, when playing at the same time, the main animation is taking priority and is freezing the effect of the outer effect.

it seems that the fade effect on the outer effect is inheriting its timing from that of the inner effect.

sorry, that's all I could think of.

**Comment by Brendonovich** [comment]
Can you please provide an example project including just the effects causing problems? Also make sure your fade smoothness isn't above 30% or so, unless you've got a super powerful computer

**Comment by D3RPSTROYER** [comment]
ah, that was the problem. I'm too trigger happy on github.

sorry 😢
