### ISSUE TITLE
Launchpad MK2 not detected

### ISSUE THREAD

**Issue by tieyee** [mat1jaczyyy/apollo-studio#378]
Im using a mk2 and windows. when i connect the launchpad to my com the launchpad configuration in settings does not show my laucnhpad. What do i do??

**Comment by mat1jaczyyy** [comment]
Please give more information.

What version of Apollo Studio are you using?

It's likely that your Launchpad firmware is out of date, or you're simply missing Novation's USB driver. You can use the [Launchpad Firmware Utility](https://fw.mat1jaczyyy.com/) to update your firmware, or get the driver from [here](https://github.com/mat1jaczyyy/apollo-studio/raw/master/Publish/novationusbmidi.exe).

**Comment by tieyee** [comment]
I am currently using 1.6.3
But will try your suggestions when I get home thank you!

**Comment by mat1jaczyyy** [comment]
Closed on Discord, issue was old MK2 firmware version
