### ISSUE TITLE
Virtual Launchpads get deleted on project load

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#380]
### Description
After creating one or more Virtual Launchpads and setting them as a track output, they don't reinitialize correctly on the next launch of Apollo.
Launching Apollo will open a Virtual Launchpad window, opening any project will not result in the Virtual Launchpad not functioning. Opening the preferences window before opening a project results in a functioning Virtual Launchpad.

### To Reproduce
Open preferences, create and lock/remember Virtual Launchpad.
Create new project, set track output as Virtual Launchpad, save, close Apollo.

1. Reopen Apollo, (VIrtual Launchpad window should open), open the newly created project
-> Virtual Launchpad is not available and is not being listed in the preferences window

2. Reopen Apollo, (VIrtual Launchpad window should open), open preferences
-> Virtual Launchpad is available in the preferences window and will be available when the project is opened

### Expected behavior
Accurate reinitialization of the Virtual Launchpad window upon launching Apollo.

### Your setup
Apollo 1.6.3
Windows 10 1903

**Comment by mat1jaczyyy** [comment]
Just loading any project will result all Virtual Launchpads to cease existence.
