### ISSUE TITLE
Undo History slow to save, resulting in backups taking a long time

### ISSUE THREAD

**Issue by Brendonovich** [mat1jaczyyy/apollo-studio#384]
### Description
Encoding Undo History takes a significant amount of time, so in situations where many backups are made quickly, significant lag can occur.

### To Reproduce
- Create Pattern device
- Select controller Launchpad for Pattern Window
- Spam buttons on Launchpad
- Observe each light taking longer to show than the last

### Expected behavior
Lights are set instantly

### Your setup
Apollo 1.7, though this also happens in 1.6
MacOS Catalina

### Additional context
Could be due to type reflection taking a long time for each undo history item, but I suspect that having hundreds of undo entries is a bit of a problem as well. Maybe don't have a separate undo entry for each time a color is changed in the pattern window?

**Comment by mat1jaczyyy** [comment]
@everyone temporary workaround: clear your undo history when this starts happening.

i wonder whether this will ping 🤔
