### ISSUE TITLE
Changing pages has a delay.

### ISSUE THREAD

**Issue by Pix3l-YT** [mat1jaczyyy/apollo-studio#386]
### Description
When changing pages with the side buttons, there is a short delay between the button press and the page change.

### To Reproduce
Open Apollo.
Create a new project, with chain selectors mapped to switching pages.

### Expected behavior
Little to no delay.

### Your setup
Windows 10 Enterprise LTSC (Build 1809), Apollo Studio | Version 1.7.0
FPS limit is at 100 FPS. However, reducing the FPS limit does reduce delay times.

### Additional context
Used to have little to no delay on older versions without multiple macros.

**Comment by SimplyMerlin** [comment]
You sure it isn't just that the macro switcher fires on delay?

**Comment by SimplyMerlin** [comment]
release*

**Comment by mat1jaczyyy** [comment]
This is intended since the beginning. The Switch device changes the page when the button is **released**, not when it's pressed, to allow a short buffer to do another input etc. Very useful if you're placing it on a regular pad à la Wormhole, but want to press a drum button at the same time.
