### ISSUE TITLE
Not really an issue but please help :D

### ISSUE THREAD

**Issue by simoncabaguio** [mat1jaczyyy/apollo-studio#392]
its my first time using apollo studio and i actually like the software. my setup is on the launchpad pro and it is running on custom firmware of mat1jaczyyy. its my first time using apollo studio so sorry if i will sound dumb. so i have ran into problems where when i press a button on the launchpad running apollo studio, the button will just light white, and i don't want that ._. , i did try using the paint device and set it to 0,0,0 so when i press the launchpad, the buttons will not light white its just blank, so when i did that and try playing my light effects, the light effects would not show up, again i am sorry if i sound dumb its my first time using apollo studio, it would be really a huge help if you can help me :D

**Comment by SimplyMerlin** [comment]
Use a key filter

**Comment by mat1jaczyyy** [comment]
Well, you say what you don't want, but what do you? What are you trying to do exactly? Are you making your own effects, or trying to play existing files?

**Comment by Pix3l-YT** [comment]
Setting the colour to 0,0,0 (black), doesn't show any light effects because the Launchpad cannot produce black lights, making Apollo not giving any colour, and not giving any light feedback.
![image](https://user-images.githubusercontent.com/66474423/93345668-49addf00-f85d-11ea-9d24-7d1958488c70.png)

**Comment by simoncabaguio** [comment]
@mat1jaczyyy im not really good at explaining but i just want to remove that white light when pressing the assigned/key filtered button, i hope this GIF could explain what i am say :D
![20200916_video](https://user-images.githubusercontent.com/71384992/93356917-5852c100-f872-11ea-9e59-62fb861e42f0.gif)

**Comment by mat1jaczyyy** [comment]
One of your other chains in the group is empty, so it's passing through all the original input signals to display on their LEDs

**Comment by simoncabaguio** [comment]
@mat1jaczyyy thank you very much :D
