### ISSUE TITLE
Empty chain before Heaven.Time-based device sometimes schedules wrongly

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#395]
### Description
Apollo Studio does not play my fade lights. I'm not sure if this is just a Launchpad MK2 issue, or that it is from Apollo.

### To Reproduce
Create a new group with one chain, that has a fade device and another that has a switch device, switching to another page.

### Expected behavior
Apollo plays the whole fade effect, rather than doing it occasionally.

### Your setup
macOS Catalina 10.15.6, Apollo Studio 1.7.0

![VID-46120610-110853-382](https://user-images.githubusercontent.com/66474423/94261655-6aacb900-ff5c-11ea-9027-38ade326c0bb.gif)

**Comment by mat1jaczyyy** [comment]
Obviously attach a minimal repro pf when reporting a specific combo like this.

**Comment by WhosPix3l** [comment]
oh right hangon lmao
[the repor.aptrk.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5283013/the.repor.aptrk.zip)

**Comment by Brendonovich** [comment]
As a workaround, you can put the Fade after all the Switches, no need for a separate group. Also makes for a cleaner chain.
![image](https://user-images.githubusercontent.com/14191578/94286842-21725e80-ff88-11ea-9849-e8838ea8f278.png)

**Comment by mat1jaczyyy** [comment]
Consistent repro: clear before pressing button.

QVBPTB8AAAABAQAAAAUAAQcCAAAAB{A6}DQnVnAQ{A26}BAEAAAAFAAEKHQEbBQAAAOgD{A:}DwPw{A5}JAAAAGT8AABk/IgAZPT8AGQwqABkAHj8ZCAA/GT0APxk/ACYZ{A>}CgGi/dJAbBP6AaL90kBtE/76fGSzeJ2T+gGi/dJAbhP3E9CtejcOU/76fGSzeJ6T+XbhKDwMrtPw{A7}PA/{A\}BEZhZGUB{A27}B{A6}==

**Comment by mat1jaczyyy** [comment]
The Fade is sent out properly but the timing goes wack

**Comment by mat1jaczyyy** [comment]
can also repro with hold
```
QVBPTC{A5}BAQAAAAUAAQcDAAAAB{A6}DQnVnAQ{A26}BAEAAAAFAQEKHQEbBQAAAOgD{A:}DwPw{A5}JAAAAGT8AABk/IgAZPT8AGQwqABkAHj8ZCAA/GT0APxk/ACYZ{A>}CgGi/dJAbBP6AaL90kBtE/76fGSzeJ2T+gGi/dJAbhP3E9CtejcOU/76fGSzeJ6T+XbhKDwMrtPw{A7}PA/{A\}BEZhZGU{A28}EAQAAAAUAAQwdARsFAAAA6AM{A:}PA/{A7}ESG9sZAE{A27}ECAAAA
```
probably renderer bug

**Comment by mat1jaczyyy** [comment]
ok i figured it out, what the hellr
