### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by saiman113** [mat1jaczyyy/apollo-studio#398]
when i pull the apollo connector in ableton it shows me "this device is not available in this version of Live"
can you help me?

**Comment by RagnaLP** [comment]
you can only use the connector in ableton suite/trial

**Comment by saiman113** [comment]
dont work in lite as well?

**Comment by RagnaLP** [comment]
lite isnt suite so it doesnt work

**Comment by saiman113** [comment]
then i can use just light effects from ableton

**Comment by RagnaLP** [comment]
you dont need the connector for apollo

**Comment by saiman113** [comment]
is their any video that could help me beacuse i have mk3 mini and i dont now how to make first cover 
thanks for help

**Comment by RagnaLP** [comment]
https://www.youtube.com/playlist?list=PLKC4R3X00beY0aB_f_ZIa3shqJX7do4mH is for lights, https://youtu.be/EZZQBwk9vd0 is for samplinga (ignore the chain based light effects part)

**Comment by saiman113** [comment]
okey thank you but how can i connect apollo and abletone whitout connector sory for questions but im beginner

**Comment by RagnaLP** [comment]
just make a track in apollo and set the output to your launchpad, everything else is in the tutorials
