### ISSUE TITLE
Apollo studio for android

### ISSUE THREAD

**Issue by SimplyMerlin** [mat1jaczyyy/apollo-studio#399]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when i can't play my apollo studio lightshows with my android phone.

### Describe the solution you'd like
I would like it if there was a app for my android phone where I can play apollo studio projects. I don't need a entire editor, I just need to be able to play the project files on android. Apollo Studio Lite or Apollo Studio Player if you will.

### Describe alternatives you've considered
idk maybe i could use a computer but ehhh i want to use my android phone

### Your setup
Android

### Additional context
im sorry

**Comment by Brendonovich** [comment]
Kappa pepeLaugh

**Comment by RagnaLP** [comment]
younipad!!!!!!!!!!

**Comment by mat1jaczyyy** [comment]
how r u gon get audio

also avalonia android is kinda broke as fuc

![image](https://user-images.githubusercontent.com/13300194/94360868-c9834700-00b0-11eb-8777-46a87d8adb52.png)

**Comment by WhosPix3l** [comment]
> how r u gon get audio
fork azors sampling on apollo thing 

> also avalonia android is kinda broke as fuc
thats why its called apollo studio player-its not the full apollo lmfao just fuck the ui up lfmaidhsdfg okbye
