### ISSUE TITLE
[macOS] Link Apollo file types with Apollo Studio

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#400]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I can't open my Apollo projects with a double click

### Describe the solution you'd like
_be able to double click pfs lmao_

### Describe alternatives you've considered
Opening Apollo Studio and selecting the project file manually

### Your setup
macOS Catalina, Apollo Studio 1.8.0

### Additional context
ok yeah this probably wont happen

**Comment by mat1jaczyyy** [comment]
Pretty sure I need to pack into a .app to do this, and to do that I need to give money to Apple, and I sure as hell won't do that.
