### ISSUE TITLE
iOS port

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#402]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when i can't play my apollo studio lightshows with my iPhone.

### Describe the solution you'd like
I would like it if there was a app for my iPhone where I can play apollo studio projects. I don't need a entire editor, I just need to be able to play the project files on iOS. Apollo Studio Lite or Apollo Studio Player if you will.

### Describe alternatives you've considered
idk maybe i could use a computer but ehhh i want to use my iPhone

### Your setup
iOS

### Additional context
im also sorry

**Comment by RagnaLP** [comment]
no.

**Comment by WhosPix3l** [comment]
sooper pods lgihts go br

**Comment by mat1jaczyyy** [comment]
no

**Comment by RagnaLP** [comment]
thank you mat

**Comment by WhosPix3l** [comment]
ok
