### ISSUE TITLE
Apollo crashing while clicking launchpad in preferences menu

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#403]
### Description
When you click on a launchpad in preferences menu, apollo is crashing

### To Reproduce
Open preferences menu, and click on the launchpad under "On-Screen Launchpad Style"

### Expected behavior
uhhh not crash

### Your setup
1.8.2

### Additional context
ty necky for finding this <3 
![obraz](https://user-images.githubusercontent.com/43300571/95664255-41884d00-0b46-11eb-90f8-f23b7d57445a.png)

**Comment by RagnaLP** [comment]
yea its been reported before, 1.8.2 doesn't utilize plugins that arent in the final version of the project, and iirc the fade of that launchpad doesnt belong to a project so it crashes or st

**Comment by mat1jaczyyy** [comment]
Uhhh not really how it works but yeah one part of Apollo is severely flawed, I fixed one bug and this bug came up instead, I need to rework a large part of it

**Comment by mat1jaczyyy** [comment]
This is the same issue as #390, so I'll close this to keep track of things easier.
