### ISSUE TITLE
Question about Fast LED Mode

### ISSUE THREAD

**Issue by NullMember** [mat1jaczyyy/apollo-studio#404]
I'm just curious about how fast led mode works. It's shame i'm too lazy to reverse engineer it.

**Comment by mat1jaczyyy** [comment]
For CFW, here's the doc and source code below it:
https://github.com/mat1jaczyyy/lpp-performance-cfw/blob/master/src/sysex/sysex.c#L46-L64

For other launchpads, we run the same code, except we compile the function into machine code and then manually patch it into the stock firmware.
https://github.com/mat1jaczyyy/LP-Firmware-Utility/blob/master/x-fast-led-hack/fast_led.c

**Comment by NullMember** [comment]
Thanks for quick reply. I'm really appreciate for your work.
