### ISSUE TITLE
Map [CTRL] / [COMMAND] + [R] to 'Replace'

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#406]
### Is your feature request related to a problem? Please describe.
I sometimes replace large amounts of light effects (as some are just the same light effect with a rotate device) if I decide to change the whole light effect.

### Describe the solution you'd like
Map [CTRL] / [COMMAND] + [R] to 'Replace'

### Describe alternatives you've considered
Right click > Replace

### Your setup
Apollo Studio 1.8.2, Windows 10

**Comment by RagnaLP** [comment]
isnt that for renaming chains

**Comment by RagnaLP** [comment]
it is dumbass

**Comment by WhosPix3l** [comment]
bruh i thought rename was only mapped to f2

**Comment by RagnaLP** [comment]
its mapped to f2?

**Comment by WhosPix3l** [comment]
yes

**Comment by RagnaLP** [comment]
ok

**Comment by mat1jaczyyy** [comment]
cmd/ctrl+shift+v should do what you want

**Comment by conc1erge** [comment]
Should we just have customizable shortcut bindings?

**Comment by mat1jaczyyy** [comment]
not in the current state, my keybind system is a HUGE mess

**Comment by mat1jaczyyy** [comment]
closing because cmd/ctrl+shift+v does what you want
