### ISSUE TITLE
Track Names not saving inside projects

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#409]
### Description
I named a track launchpad lights and saved using the latest version of apollo studio (1.8.3)
Then when I open another project, and the project where I renamed the track, its name gets reverted back to Track 1

### To Reproduce
Open any project, rename the track to any name besides the original, close the project and open any other project, then open back the project with the renamed track, it will revert back...

### Expected behavior
For track names to be saved in the approj file.

### Your setup
Apollo 1.8.3
Windows 10 64-bit

**Comment by YarostheLaunchpadder** [comment]
Btw after restarting apollo the track name gets loaded in the project again, basically it doesn't refresh the name of the track, shows the name of the track of the last loaded project, but the track itself works fine, loads normally

**Comment by mat1jaczyyy** [comment]
Can't repro this one... are you sure about the issue? Can you record a video if it actually happens?

**Comment by YarostheLaunchpadder** [comment]
I think it was a bug that happened only once, now after restarting apollo it's gone, plus the bug is insignificant. So I close the issue.
