### ISSUE TITLE
API for other developers?

### ISSUE THREAD

**Issue by RaddedMC** [mat1jaczyyy/apollo-studio#410]
I haven't yet tried Apollo but it seems really cool and as a (now past) user of Live Lite, Apollo looks like it would be a massive help for my Launchpad projects.
I'm wondering if you're planning on adding an API so other developers can integrate other RGB devices to Apollo? I'd love to adapt my [ChromaMidi](https://github.com/RaddedMC/ChromaMidi) program to it!

**Comment by mat1jaczyyy** [comment]
We are against a public API as it would cause massive segregation and fragmentation of the userbase, as we see today with the M4L scene on Ableton Live; as well as ensuring Apollo stays high-quality software. 

For this specific reason, Apollo is open-source and you can add support for other MIDI hardware devices by modifying Launchpad.cs with a new LaunchpadType to support them, and make a pull request for all users to enjoy as built-in functionality.

Apollo is heavily tied to the physical 10x10 light format (many devices use native X and Y directions), so we suggest your implementations follow it closely and don't map indexes to arbitrary real-world positions.

**Comment by RaddedMC** [comment]
Ah, I can work with that then. Thanks for letting me know!
What exactly do you mean by mapping indexes to arbitrary positions? Can you provide an example with a midi device that doesn't have a 10x10 grid?

**Comment by mat1jaczyyy** [comment]
Right now there are none, but for example adding support for something like Underlights would require significant remapping to arbitrary positions on the LED strip
