### ISSUE TITLE
Let us translate Apollo to our native language!

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#411]
### Is your feature request related to a problem? Please describe.
Not necessarily a problem, but might just grow Apollo Studio even more to people who can't read English.

### Describe the solution you'd like
Release a file that we can edit to translate Apollo.

### Describe alternatives you've considered
not sure if an alternative exists

### Your setup
Apollo Studio 1.8.3 / Windows 10 + Ubuntu Linux + macOS 10.15 ;)

**Comment by mat1jaczyyy** [comment]
![image](https://user-images.githubusercontent.com/13300194/97192795-919f1a80-17a8-11eb-9f3a-9f7bff2ba230.png)
please check existing issues before making an issue
