### ISSUE TITLE
[macOS?] Apollo triggers all chains on a multi device

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#414]
### Description
Apollo triggers all chains inside the multi device.

### To Reproduce
* Create a shape with a pattern device
* Make eight chains inside a multi device each containing different fade colours

### Expected behavior
to not do that lmao

### Your setup
Apollo Studio 1.8.3, macOS Catalina 10.15.6

### Additional context
![image](https://user-images.githubusercontent.com/66474423/97845003-8f940900-1d1e-11eb-8ab6-8e6d7eb4084b.png)

Apollo chain: `QVBPTC{A5}BAQAAAAQFAAAABQABDgE{A9}y{A5}UAARUB{A<}8D8{A<}EAAAAGh0BGwEAAADoAwAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGT8/Pxk/Pz8ZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAaHQEbAQAAAOgDAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABk/Pz8ZPz8/GT8/Pxk/Pz8ZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABodARsBAAAA6AMAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZPz8/GT8/Pxk/Pz8ZPz8/GT8/Pxk/Pz8ZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGh0BGwEAAADoAwAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGT8/Pxk/Pz8ZPz8/GT8/Pxk/Pz8ZPz8/GT8/Pxk/Pz8ZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABk{AC}UAAQsC{A5}QUAAQsD{A5}QUAARAE{A6}dDaGFpbiAjAQ{A26}C{A5}QBAAAABQABCh0BGwQAAADoAw{A:}8D8{A6}gAAABk/AAAZPz8/{AB}DwPw{A5}BAQAAAANSZWQB{A27}EAQAAAAUAAQodARsEAAAA6AM{A:}PA/{A6}IAAAAZPyAAGT8/Pw{AB}8D8{A6}Q{A5}GT3JhbmdlAQ{A26}BAEAAAAFAAEKHQEbBAAAAOgD{A:}DwPw{A5}CAAAAGTo/ABk/Pz8{AB}PA/{A6}E{A5}BlllbGxvdwE{A27}QBAAAABQABCh0BGwQAAADoAw{A:}8D8{A6}gAAABkJPwAZPz8/{AB}DwPw{A5}B{A6}VHcmVlbgE{A27}QBAAAABQABCh0BGwQAAADoAw{A:}8D8{A6}gAAABkAIT8ZPz8/{AB}DwPw{A5}B{A6}RCbHVlAQ{A26}BAEAAAAFAAEKHQEbBAAAAOgD{A:}DwPw{A5}CAAAAGQQAPxk/Pz8{AB}PA/{A6}E{A5}BkluZGlnbwE{A27}QBAAAABQABCh0BGwQAAADoAw{A:}8D8{A6}gAAABkbAD8ZPz8/{AB}DwPw{A5}B{A6}ZQdXJwbGUB{A27}EAQAAAAUAAQodARsEAAAA6AM{A:}PA/{A6}IAAAAZPAA/GT8/Pw{AB}8D8{A6}Q{A5}EUGluawE{A27}EH{A:}dSYWluYm93AQ{A26}`

[heres a .zip i guess.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5473577/heres.a.zip.i.guess.zip)

**Comment by mat1jaczyyy** [comment]
This is exactly what the preprocessing chain is for, you should try placing
your Pattern there

**Comment by WhosPix3l** [comment]
ok cool it works now lol thanks
