### ISSUE TITLE
[macOS] Apollo crashes when clicking on a chain

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#415]
### Description
If an infinite light effect inside a choke is running, clicking on another chain will crash Apollo.

EDIT: not inside a choke, the effect is after the choke as shown in the chain

### To Reproduce
* Download my Apollo chain
* Run the infinite light effect
* Click on another chain

### Expected behavior
to not crash lmao

### Your setup
Apollo Studio 1.8.3, macOS Catalina 10.15.7
EDIT: it wasnt 10.15.6 lmao my apologies

### Additional context
![Screen Recording 2020-11-03 at 10 15 20](https://user-images.githubusercontent.com/66474423/97946963-66c35080-1dbe-11eb-8fe0-ef26f9e6a965.gif)

[lè chain.apdev.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5479177/le.chain.apdev.zip)

**Comment by TheMarkTwo** [comment]
Could you send the crash report file and the chain here?

**Comment by WhosPix3l** [comment]
doesn't log the crash :/ i had to force quit it to continue using apollo

**Comment by mat1jaczyyy** [comment]
can you consistently reproduce? sounds like midi port dead to me

**Comment by WhosPix3l** [comment]
pretty sure it happens every time. well on my hackintosh at least

**Comment by mat1jaczyyy** [comment]
doesnt repro for me on windows, will try macos later

**Comment by mat1jaczyyy** [comment]
repro'd on macos
