### ISSUE TITLE
multiple launchpad pattern

### ISSUE THREAD

**Issue by RagnaLP** [mat1jaczyyy/apollo-studio#416]
### Is your feature request related to a problem? Please describe.
no

### Describe the solution you'd like
a way to have multiple launchpads on a pattern device instead of needing to use the output device and key filters and stuff idk

### Describe alternatives you've considered
output device but thats broken and takes longer i think idk

### Your setup
computer
launchpad x
windows 10 insert build number here too lazy to check
ok

### Additional context
ye

**Comment by mat1jaczyyy** [comment]
We said no https://github.com/mat1jaczyyy/apollo-studio/issues/79

**Comment by RagnaLP** [comment]
o sry
