### ISSUE TITLE
Launchpad Rotation doesn't work if fast LED Optimizer is used

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#417]
### Description
If the Launchpad has modded fast LED firmware, the Rotation setting in the Preferences is ignored, causing LEDs to display incorrectly.

### To Reproduce
1. Use a Launchpad with fast LED support (cfw or modded stock)
2. Set Rotation to anything other than 0 degrees
3. Send LEDs

### Expected behavior
The LED positions should rotate before the optimization happens.

### Your setup
Any

**Comment by RagnaLP** [comment]
ig use rotate device then?

**Comment by WhosPix3l** [comment]
won't work as the rotate device only rotates light effects, and doesn't rotate the keys on the key filter

**Comment by RagnaLP** [comment]
oops

**Comment by TheMarkTwo** [comment]
"mine"
