### ISSUE TITLE
Choosing which frame to post process from pattern editor

### ISSUE THREAD

**Issue by PadBoy** [mat1jaczyyy/apollo-studio#419]
### Is your feature request related to a problem? Please describe.

It's a feature request. I'd like to see a feature where I can choose a frame from the 'Pattern Editor' to post process it without affecting the other drawn frames.

### Describe the solution you'd like

A new device would be easy I think, just by putting after a 'Pattern Editor' and selecting in a dropdown or a dial which frame I'd like to work with. If the device is not there it behaves like normlas and process the whole light coming from the 'Pattern Editor'. Also an image prview of the selected frame would be a good idea.
Or adding a checkbox to the 'Pattern Editor' in the chain with the name of something like "Frame Post Process Mode", which would allow to do the above mentioned feature.

### Describe alternatives you've considered

I have not found any alternatives or ways to do it myself.
### Your setup

Windows 10, 1903 build
Apollo Studio 1.8.3
### Additional context

The new device could be inside containers with the name of 'Advanced Pattern Editor' or something like.

**Comment by mat1jaczyyy** [comment]
@rpgaleksy thought

**Comment by rpgaleksy** [comment]
Some use-cases would be nice since from my point of view this might end up being a decently sized change.
The idea itself is interesting but if it's a very specific niche thing you might be better off finding another way to achieve a similar effect with the given tools.

**Comment by mat1jaczyyy** [comment]
Smells of too specific and too feature creep. Personally for these rare situations I'd color-code frames and use Color Filters afterwards. Closing...
