### ISSUE TITLE
Closing Pattern Editor while playing effect locks up Heaven

### ISSUE THREAD

**Issue by RagnaLP** [mat1jaczyyy/apollo-studio#420]
### Description
The launchpad does not display any lights

### To Reproduce
Make an effect in the pattern editor, start playing it, and while it is playing, close the pattern editor.

### Expected behavior 
not do that i guess idk

### Your setup
Windows 10 Pro, Apollo Studio Version 1.8.3

### Additional context
yes

**Comment by WhosPix3l** [comment]
To add, this bug cannot be consistently reproduce.
Spamming the Launchpad will sometimes show the button added to the pattern but is not common.
Terminal will sometimes say `Unhandled exception while receiving MIDI signal' (or something along those lines)

**Comment by mat1jaczyyy** [comment]
Repro'd
