### ISSUE TITLE
Duplicating a Track doesn't properly initialize Fade device

### ISSUE THREAD

**Issue by OrinoLP** [mat1jaczyyy/apollo-studio#422]
### Description
duplicating a track and changing the input to apollo connector crashes the application 

### To Reproduce
change the input to apollo connector after duplicating the track

### Your setup
Apollo Version: Version 1.8.3
Operating System: Microsoft Windows 10

### Additional context
[Crash-1611664668.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5873503/Crash-1611664668.zip)
[Crash-1611664800.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5873505/Crash-1611664800.zip)

**Comment by conc1erge** [comment]
Have had this issue before, thought it was Ableton and Max being stupid.

**Comment by mat1jaczyyy** [comment]
repro'd

**Comment by mat1jaczyyy** [comment]
doesn't require connector to repro
