### ISSUE TITLE
y u no linux?

### ISSUE THREAD

**Issue by dromer** [mat1jaczyyy/apollo-studio#423]
Any instructions on how to build this in non-win, non-mac environments? :)

**Comment by mat1jaczyyy** [comment]
We do run on Linux, albeit you'll have to build it yourself: https://github.com/mat1jaczyyy/apollo-studio/issues/364
Big problem with that is that we use a decades old version of Avalonia that isn't available on NuGet anymore, so you can't build anything yourself. I've been trying to get this fixed for a while (https://github.com/mat1jaczyyy/apollo-studio/pull/394)

You should contact me on Discord: https://discord.gg/pjDWeeJT

**Comment by dromer** [comment]
Thnx for the detailed reply. Depending on decades old dependencies sounds like a bit of a risk though ..

Btw, it might also be interesting to integrate this with the Ctlra effort over at OpenAV: https://github.com/openAVproductions/openAV-Ctlra
