### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by OrinoLP** [mat1jaczyyy/apollo-studio#425]
### Description
when trying to set up virtual launchpad apollo crashes 

### To Reproduce
setting>the plus button.virtual launchpad 
### Expected behavior
virtual launchpad to work as intended and not crash 
### Your setup
Windows 10.0.18362
Apollo Version: Version 1.8.4
### Additional context
[Crash-1612859684.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5949957/Crash-1612859684.zip)

**Comment by mat1jaczyyy** [comment]
Dupe of #390
