### ISSUE TITLE
Crash/Freeze after Hold Device w/Release

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#428]
### Description
After this combination of devices 
![obraz](https://user-images.githubusercontent.com/43300571/109466077-6fc0e780-7a69-11eb-8b3d-7512a6fc30b2.png)
when you try to play the effect, apollo crashes.

### To Reproduce
Get a normal 8 page template (might work without, idk). And than put a chain which contains: **Key Filter**, **Pattern**(whatever works here), **Fade**: start with `000000` and end on `3F3F3F`... Duration and gate should not matter here. After that put a **Hold** device with I**nfinite** and **Release**. And than play the light effect. Apollo should crash. 

### Expected behavior
Not crash?

### Your setup
Win10, Apollo - 1.8.4

**Comment by mat1jaczyyy** [comment]
send an exported chain / devices

**Comment by Tuchan** [comment]
https://cdn.discordapp.com/attachments/379032750617001984/815852438769893436/aaa.apchn

**Comment by mat1jaczyyy** [comment]
need to try repro later

**Comment by mat1jaczyyy** [comment]
@Brendonovich clean repro with preview showing obvious wtf

[428.zip](https://github.com/mat1jaczyyy/apollo-studio/files/6097398/428.zip)
