### ISSUE TITLE
Pattern: Frame staying on launchpad after exiting w/Apollo Connector

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#429]
### Description
When you connect Launchpad through Apollo Connector and use `Pattern`, after exiting from `Pattern` device, last frame you saw on your launchpad should now freeze and always be on the launchpad unless you clear it.

### To Reproduce
Connect Launchpad through Apollo Connector, open Pattern, Draw something, exit.

### Expected behavior
The Frame should disappear. The correct behavior is presented when you connect your launchpad normally, not through Apollo Connector.

### Your setup
win10, 1.8.4

### Additional context
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by WhosPix3l** [comment]
i've had this issue for a while now, but i was too lazy to report lmao. glad someone did tho!

also nice context
