### ISSUE TITLE
Long press bug with Pattern-function

### ISSUE THREAD

**Issue by jonasxjon** [mat1jaczyyy/apollo-studio#430]
### Description
I have the problem, that, when I have a Pattern-Device in my chain and press longer than a second on a button, the button-light stays white after the pattern animation. Not sure if this is a bug or I'm just haven't found the right checkbox to fix that. 

### To Reproduce
1. In my Chain I have a Pattern-Device and a Fade-Device
2. Long press a button of the launchpad
3. The button stays white after firing the animation

### Expected behavior
After long pressing a button it should not be staying white 
### Your setup
macOS Catalina 10.15.4, Apollo 1.8.4, Launchpad X 

### Additional context
The reason why I need the long press and can't just press short, is, that I don't want to do a regular prepared cover but to play Piano-Style on the launchpad. So for chords for example I have to press mostly longer than a second on multiple buttons. 

Its a really awesome tool that you've build with Apollo. Thank you so much for all your effort 🙌

**Comment by Tuchan** [comment]
please send the chain or project
it kinda seems like you did something weird there >:(

**Comment by mat1jaczyyy** [comment]
please export the chain this occurs with so we can test exactly what's happening in your setup

**Comment by jonasxjon** [comment]
Hey, you are really fast in responding :) Thanks a lot. Its a really basic project, cause I first wanted to try all the functions of Apollo. 

@Tuchan after you've said, that this is weird, I've tried to delete everything and recreate my chain... and then the problem wasn't there anymore. So I've going back with 'Undo' till this status: 
[Apollo03.approj.zip](https://github.com/mat1jaczyyy/apollo-studio/files/6060862/Apollo03.approj.zip)

Seems like it has something to do with the Tone-device. When I've added it the long-press-problem started. 

Even if I delete the Tone-device the long-press-problem is still there. But like I've said, when I rebuild the project with just the Pattern- and Fade-device its works perfectly fine. Really a strange bug.

**Comment by Tuchan** [comment]
ok first of all... that method works, but i feel like there is a better way to achive this effect
https://cdn.discordapp.com/attachments/781270185763799043/815913636127178802/asdasd.apdev

If you do not understand anything about apollo, I suggest reading the [wiki](https://github.com/mat1jaczyyy/apollo-studio/wiki) or watching the [yt tutorial series](https://www.youtube.com/watch?v=eZf5SgNJcqk)

If you want to grab a `8 page setup template` or auto `mode light` "device" you can get them [there](https://sites.google.com/view/tuchan/downloads)

also, I did not experience the bug you described... it might be a "you" problem but im not sure, please provide more info :)

**Comment by jonasxjon** [comment]
@Tuchan Thank you for your advice and your quick response. Yeah thats a easier method to get that effect 👍I've just startet with Apollo and really looking forward to get deeper into that topic :)

**Comment by jonasxjon** [comment]
@Tuchan Just came across an other problem – maybe you have an idea how to fix that. 

The fans of my MacBook Pro 2014 are turning up like crazy cause of the high CPU-Usage of Apollo (see Screenshot) Is there anything I can do about it?
<img width="959" alt="Bildschirmfoto 2021-03-01 um 17 59 33" src="https://user-images.githubusercontent.com/79835581/109531367-18963380-7ab8-11eb-8deb-bed1464a0aba.png">

**Comment by Tuchan** [comment]
@mat1jaczyyy ?

**Comment by jonasxjon** [comment]
Thank you @Tuchan 

@mat1jaczyyy 
The problem came up while following the tutorial 5 for Apollo on youtube and the color fade running in the background. Maybe you have some tips for settings for older Macs/PCs? :)

**Comment by mat1jaczyyy** [comment]
@jonasxjon While rendering an effect, Apollo will fully utilize one CPU core in order to synchronize the timings as accurately as possible. This is super important for achieving good smoothness on Fade effects on high FPS. There's not much we can do about this. While you're idling / designing an effect (not running lights on the Launchpad actively), it should not use any CPU, because you aren't doing anything at the time.

As far as your effect goes, you had the white LED coming up because there was a second empty Track in addition to the primary one you were making your effects in, and a bug in my code caused it to erroneously display a white LED on release. That's a legitimate Apollo bug, not your fault, I'll have this fixed for 1.8.5 soon. Thanks for reporting 👍
