### ISSUE TITLE
How do I use Multi?

### ISSUE THREAD

**Issue by Stebanourlso** [mat1jaczyyy/apollo-studio#431]
### Your setup
Windows, Apollo 1.8.4

**Comment by RagnaLP** [comment]
watch the tutorial and use issues properly

**Comment by mat1jaczyyy** [comment]
https://youtu.be/VEDKdez4iCY?t=399
https://github.com/mat1jaczyyy/apollo-studio/wiki/4.-Device-Reference#multi
