### ISSUE TITLE
Automatically import a group when creating a new track

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#432]
### Is your feature request related to a problem? Please describe.
No. I want Apollo to add a group device when I create a new track and when I make a new project.

### Describe the solution you'd like
A feature in Apollo where you can add a group device to every track automatically

### Describe alternatives you've considered
Importing my template group everytime a project is started.

### Your setup
Windows 10 Professional, build 21332 Insider
Apollo 1.8.4

### Additional context
![image](https://user-images.githubusercontent.com/66474423/112135472-65c17d00-8c00-11eb-9acb-c9901915b271.png)
sick mockup amirite

**Comment by WhosPix3l** [comment]
oh yeah selecting an .aptrk could work too

**Comment by mat1jaczyyy** [comment]
honestly i'd avoid storing tracks/chains/devices in the preferences solely due to the existence of the output device

**Comment by WhosPix3l** [comment]
ok
