### ISSUE TITLE
Device that triggers when launchpad loads

### ISSUE THREAD

**Issue by SimplyMerlin** [mat1jaczyyy/apollo-studio#433]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
A device that sends a midi signal when the launchpad gets loaded to the chain, this will be useful if you use your launchpad as a macropad or just want a idle animation in your setup from your launchpad.

### Describe alternatives you've considered
A midi note that just gets sent instead of a device, not sure how you'd implement it though without switching up the layout on the keyfilter device

### Your setup
Windows 11, latest apollo

### Additional context
stop playing ppt pls make this

**Comment by WhosPix3l** [comment]
windows 11

**Comment by RagnaLP** [comment]
smh, i use linux 2

**Comment by WhosPix3l** [comment]
imagine not using macos 420.69 weed cringe bro

**Comment by SimplyMerlin** [comment]
> 
> 
> smh, i use linux 2

https://aws.amazon.com/amazon-linux-2/

**Comment by RagnaLP** [comment]
> > smh, i use linux 2
> 
> https://aws.amazon.com/amazon-linux-2/

fgs merlin it is unreleased operating system do not leak it!!!
