### ISSUE TITLE
Compatible with Apollo? 

### ISSUE THREAD

**Issue by McBumberSnatcher** [mat1jaczyyy/apollo-studio#434]
I found Apollo and I was wondering what my options are since it doesn't LOOK like my pad is compatible but I was just wondering 

My setup is a novation Launchpad Mini. I would use Ableton Live but I lost the sheet of paper that let me use it.

**Comment by RagnaLP** [comment]
what launchpad mini do you have

**Comment by McBumberSnatcher** [comment]
![Uploading image.jpg…]()

**Comment by mat1jaczyyy** [comment]
@McBumberSnatcher you submitted the comment too early, the image didn't upload in time.

**Comment by McBumberSnatcher** [comment]
![image](https://user-images.githubusercontent.com/75403108/112677091-47919200-8e37-11eb-990f-56344d0f536c.jpg)

**Comment by RagnaLP** [comment]
not compatible

**Comment by mat1jaczyyy** [comment]
@McBumberSnatcher sorry, but we don't support non-RGB launchpad models. our engine is built specifically to take advantage of RGB capabilities found on newer models

**Comment by McBumberSnatcher** [comment]
Is this one compatible 
![image](https://user-images.githubusercontent.com/75403108/112679430-2a11f780-8e3a-11eb-9ee8-23a699d8455f.jpg)

**Comment by rpgaleksy** [comment]
Yes, since it is an RGB Launchpad.
