### ISSUE TITLE
Crash when dropping onto scrollbar

### ISSUE THREAD

**Issue by OrinoLP** [mat1jaczyyy/apollo-studio#436]
### Description
apollo crashed when I moved delay

### To Reproduce
not entirely sure if it was purely because of me moving it so I don't really know how to reproduce it

### Expected behavior
not crash 

### Your setup
Apollo Version: Version 1.8.4
Operating System: Microsoft Windows 10.0.18362

**Comment by WhosPix3l** [comment]
update apollo?

**Comment by RagnaLP** [comment]
HAHAHAHA I JUST REALISER

**Comment by mat1jaczyyy** [comment]
1.4.1 is kind of ancient, please attach a crash log and make sure to update as well

**Comment by OrinoLP** [comment]
normally apollo asks me to update when I launch it

**Comment by OrinoLP** [comment]
[Crash-1583488555.zip](https://github.com/mat1jaczyyy/apollo-studio/files/6414671/Crash-1583488555.zip)

**Comment by OrinoLP** [comment]
[Crash-1620028168.zip](https://github.com/mat1jaczyyy/apollo-studio/files/6414681/Crash-1620028168.zip)
 accidentally uploaded the wrong log lol the right one is ^

**Comment by mat1jaczyyy** [comment]
@OrinoLP where did you attempt to drop the device? can you reproduce the crash?

**Comment by OrinoLP** [comment]
just tried dropping it in front of the chain, cant seem to reproduce the crash

**Comment by mat1jaczyyy** [comment]
repro'd, crashes when you drag drop it onto the scrollbar of the group. nice find 👍
