### ISSUE TITLE
[macOS] Apollo auto-update not working

### ISSUE THREAD

**Issue by WhosPix3l** [mat1jaczyyy/apollo-studio#438]
### Description
Title says it all, auto-update not working on macOS

### To Reproduce
Click update Apollo on the bottom bar thing yes

### Expected behavior
to update lmao

### Your setup
macOS 10.13.6 "High Sierra"
Apollo Studio 1.8.4

### Additional context
Terminal log: https://pastebin.com/raw/TsLf03Z1

**Comment by SimplyMerlin** [comment]
try using the latest version LULW

**Comment by mat1jaczyyy** [comment]
is this portable (zip) version or installed (pkg) version of 1.8.4 that you have

**Comment by WhosPix3l** [comment]
it's installed

**Comment by mat1jaczyyy** [comment]
triple checked and it works
