### ISSUE TITLE
Apollo Crashes on clicking virtual launchpad in settings (Minor bug)

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#439]
### Description
This is just interesting, noticed this bug recently, this is not something important, it was just interesting to report. It currently happens on Windows, not tested on Mac as I don't own one.

### To Reproduce
Go to apollo settings and click or drag on the launchpad that should show the light effects, this one:

![image](https://user-images.githubusercontent.com/54041533/124762507-42aea500-df33-11eb-9a70-03723d6d3739.png)
 
Also note that it does happen with lower FPS too, I just set it to 500 because my PC can handle it
### Expected behavior
The launchpad displays the smoothness of the lights depending on the FPS set.

### Your setup
Windows 10 64-bit
Apollo V1.8.7

### Additional context
My **guess**, I'm not sure, but I think it happens after the update with the heaven renderer and the UI wasn't updated to work with the new FPS system, thus causing the crash. I haven't run apollo in an IDE as Visual Studio Code and can't confirm, just a guess on what to look! But it can easily can be confirmed by looking at the console, well, why I'm saying that, you obviously know that 😂 I'm just too lazy to clone the code and set up the environment XD

**Comment by mat1jaczyyy** [comment]
jeez has it been a year yet

**Comment by YarostheLaunchpadder** [comment]
Yeah, ok, closing this as it has been reported multiple times already, just haven't seen the previous reports.
