### ISSUE TITLE
Launchpad Mini Support

### ISSUE THREAD

**Issue by rasoolZero** [mat1jaczyyy/apollo-studio#440]
### Is your feature request related to a problem? Please describe.
welp, the problem is that I have a Launchpad Mini and I can't use Apollo

### Describe the solution you'd like
I'd really like this model to be supported by Apollo

### Your setup
Windows 10, latest version

### Additional context
I really appreciate your hard work, if I wasn't in a sanctioned country, I'd definitely donate to this amazing project

**Comment by WhosPix3l** [comment]
Hi,

This Launchpad model will never be supported by Apollo, as it does not have the RGB capabilities the newer models have.

Also, please search for existing issues like these before making a new one.

Thank you!
