### ISSUE TITLE
multi language

### ISSUE THREAD

**Issue by Jikexiaobai** [mat1jaczyyy/apollo-studio#441]
There are many users around me who want to use Apollo for lighting creation, but they don’t speak English. I don’t want to change Apollo too much. I think adding multi-language features will make it easier to use and more users will become Producer of the project file. I hope to increase the import of language files in the settings, or put the files in a certain directory of Apollo to load it.

**Comment by mat1jaczyyy** [comment]
Duplicate of #166. We won't be officially supporting any form of translations. They make code unnecessarily complicated, and it fragments the user base and learning material.
