### ISSUE TITLE
Spamming "On-Screen Launchpad Style" in settings crashes apollo

### ISSUE THREAD

**Issue by PANOSKPT** [mat1jaczyyy/apollo-studio#442]
I opened settings and accidentally spammed the "On-Screen Launchpad Style" launchpad and suddenly apollo closed.
I didn't lose any of the data because apollo had a very recent backup. I tried replicating it and it happened with all launchpad styles (standard, diagonal, stock, phantom, sanded, and all models of launchpad).

**Comment by rpgaleksy** [comment]
Confirming this behavior for version 1.8.7.
From my experience, it is enough to just click a pad on the on-screen Launchpad preview once to crash Apollo,

**Comment by mat1jaczyyy** [comment]
this has to be like the 6th time this was duped lmao
okay, here's the trick to get myself to fix it:
if i dont fix it by 2022 im gay

**Comment by mat1jaczyyy** [comment]
this has to be like the 6th time this was duped lmao
okay, here's the trick to get myself to fix it:
if i dont fix it by 2023 im gay

**Comment by WhosPix3l** [comment]
2023 wtf
also arent you already gay lmao

**Comment by rpgaleksy** [comment]
We already know you can suck a golf ball through a garden hose though so take your time to fix it good lol

**Comment by mat1jaczyyy** [comment]
😳

**Comment by conc1erge** [comment]
the clock is ticking
