### ISSUE TITLE
Crash if .stats or .config is a hidden file

### ISSUE THREAD

**Issue by Peranoid** [mat1jaczyyy/apollo-studio#445]
Hey friends,

i have a major issue here. I worked with apollo before and made lights but aftrer i got my launchpad pro mk3 i cant use apollo anymore. I looked up what driver i need and i have the 2.22.0.10 novation usb driver but still cant make apollo start. I dont know whats the problem here, i reinstalled the driber and apollo several times but still nothing...

**Comment by WhosPix3l** [comment]
What does it say upon startup?





also pls use provided template ty

**Comment by Peranoid** [comment]
it doesnt say anything. It wont start at all. not even in the background

**Comment by mat1jaczyyy** [comment]
Check your Crashes folder and see if there are any recent crashes, upload them here if possible, otherwise all we can do is guesswork.

The crashes folder is located at `C:\Users\<username>\.apollostudio\Crashes\`.

**Comment by WhosPix3l** [comment]
oh yeah forgot about that

**Comment by mat1jaczyyy** [comment]
After Discord call, crash happens because this line:

https://github.com/mat1jaczyyy/apollo-studio/blob/230e6dbaa311e3d9fb373db9642f4c81b89d8673/Apollo/Core/Preferences.cs#L406

Throws UnauthorizedAccessException if the file is hidden for some reason. lol....
