### ISSUE TITLE
Does Apollo need Max for Live to work?

### ISSUE THREAD

**Issue by RaddedMC** [mat1jaczyyy/apollo-studio#447]
### Describe your inquiry
I'm hoping to get back into making Launchpad videos, but Max for Live's price poses a huge barrier for re-entry. Does Apollo need Max for Live to work?

**Comment by mat1jaczyyy** [comment]
@RaddedMC It is not necessary. Some minor additional functionality can be unlocked with M4L, but it is absolutely not required at all.

**Comment by RaddedMC** [comment]
Great, thanks for letting me know! Maybe I just didn't set things up right when I first tried Apollo Studio.
To add on to my original question, what version of Live does it need to work? I just have the Live 11 lite that came with my Launchpad MK2.

**Comment by mat1jaczyyy** [comment]
It works with any version of Live, or any DAW for that matter. You could
use FL Studio if you so preferred.
