### ISSUE TITLE
Terminal error (OSX 10.14.6) when opening apollo

### ISSUE THREAD

**Issue by PadBoy** [mat1jaczyyy/apollo-studio#449]
### Description
When I open Apollo 1.8.8 on my computer I get this error in the terminal:

Last login: Fri May 13 13:57:38 on ttys000
Szabo-Mac-mini:~ mateszabo2001$ /Users/mateszabo2001/Downloads/Apollo-1.8.8-Mac/Apollo/Apollo ; exit;
Failed to create CoreCLR, HRESULT: 0x80004005
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Folyamat befejeződött]

### To Reproduce
Open Apollo on Mac OS 10.14.6 (Mojave)

### Expected behavior
Starting apollo studio

### Your setup
OSX 10.14.6 (Mojave), Apollo 1.8.8

### Additional context
![Képernyőfotó 2022-05-13 - 14 22 33](https://user-images.githubusercontent.com/53392547/168282325-02f8793b-cc34-4208-92be-1d98932499c7.png)

**Comment by mat1jaczyyy** [comment]
iirc if you reboot this goes away?

**Comment by PadBoy** [comment]
Yes it goes away, but there is no icon to start and the terminal starts to spam "Rescan"

**Comment by mat1jaczyyy** [comment]
if the terminal is spamming rescan it means the app has started running, the main apollo window should show up shortly after rescanning log shows up
