### ISSUE TITLE
how to open a lunchpad work

### ISSUE THREAD

**Issue by lianwangyunuo** [mat1jaczyyy/apollo-studio#450]

**Comment by mat1jaczyyy** [comment]
yes

**Comment by rpgaleksy** [comment]
```
Step 1: Go to the cafeteria.
Step 2: Bring a pad.
Step 3: Put lunch from cafeteria on pad.
Step 4: open
Step 5: ??
Step:
Step 69: Free your stuck step-sister.
Profit
```

But seriously, what is this issue even supposed to be about?
With a question (?) like that you could just join the Apollo Studio Discord server and ask it there.

**Comment by pnxl** [comment]
first of all you have to throw the lunch of the pad to your screen with apolo studio open
you opened the lunch pad
