### ISSUE TITLE
Multi Device setup

### ISSUE THREAD

**Issue by AGWlaunchpad** [mat1jaczyyy/apollo-studio#451]
### Describe your inquiry
I've recently gotten some more launchpads and needed a way to create multi device projects (so I got Apollo). It has been fine playing some single covers, but when I started setting up a double LP cover, only one of the LP's ports showed up.

### Your setup
MacOS 12.2, Apollo 1.8.8 & multiple LP pro MK3s

### Additional context
<img width="349" alt="Screen Shot 2022-05-31 at 3 39 39 PM" src="https://user-images.githubusercontent.com/106582189/171121240-765751ce-d429-4783-af71-83c011633739.png">

**Comment by mat1jaczyyy** [comment]
go into bootloader and give each of your devices a different ID

**Comment by mat1jaczyyy** [comment]
resolved in discord - needed to rename device in audio&midi setup
