### ISSUE TITLE
Copy device isn't refreshing button information in a specific scenario

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#453]
### Description
Having 2 copy devices and changing the offset property while playing a light effect, causes it to temporarily freeze specific buttons (until you clear the launchpad or restart the project)

### To Reproduce
1. Have 2 copy devices after each other
![obraz](https://user-images.githubusercontent.com/43300571/200198018-88c825a9-55fa-4c37-8841-ddd2d0262f06.png)
and hold one offset property and move it.
2. Play the light effect while still holding the mouse button. Then release it.
3. Now move the offset position to it's previous state NORMALLY.
4. Now you should see that certain buttons are frozen.

### Expected behavior
Not to freeze

### Your setup
Win 10
apollo 1.8.8

### Additional context
https://user-images.githubusercontent.com/43300571/200198765-11418ddd-128a-464a-b78f-63c47d7f3e93.mp4

**Comment by mat1jaczyyy** [comment]
If you trigger devices while changing their parameters, Apollo provides no guarantee they'll work correctly, so this is kinda intended. Set your parameters, and then trigger your devices
