### ISSUE TITLE
Grouping and Choking crashes

### ISSUE THREAD

**Issue by losowyLP** [mat1jaczyyy/apollo-studio#458]
### Description
When grouping multiple effects (both with Ctrl+G and the context menu) the app just straight up crashes.

### To Reproduce
Make a line of effects and try grouping them.

### Expected behavior
for apollo not to crash lol

### Your setup
Windows 10 22H2
Apollo Studio Version 1.8.10

**Comment by mat1jaczyyy** [comment]
Thanks for the report, was actually aware of this one already over Discord
but haven't gotten around to fixing yet. Will fix as soon as possible 👍
