### ISSUE TITLE
Apollo not dectecting my Launchpad S

### ISSUE THREAD

**Issue by Psychosfun** [mat1jaczyyy/apollo-studio#463]
Hi there!

I'm trying to connect my Launchpad S to Apollo Studio, but it's not dectecting anything.
Is Apollo working with the Launchpad S, first of all?

I'm using it on Windows 10,  on the version 1.8.13 of Apollo Studio.

The pad was connected before starting the software, I also installed Novation USB Midi, and I'm only using Apollo Studio with the Launchpad. 

Thank you very much in advance.

**Comment by mat1jaczyyy** [comment]
intended, only rgb launchpads are supported

**Comment by Psychosfun** [comment]
In other words, Launchpad S will not work with the software?

**Comment by conc1erge** [comment]
> In other words, Launchpad S will not work with the software?

yes, it won't work since Apollo is specifically designed for full RGB Launchpads

**Comment by Psychosfun** [comment]
Ok ok, thank you two for your answers.
Have a lovely day.
