### ISSUE TITLE
Apollo crashes when sending notes while loading a project

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#465]
### Description
Whenever you load a project in Apollo and send a note via Apollo Connector, Apollo crashes with no way to restore the project via the popup at the start.

### To Reproduce
1. Have Apollo project saved with Apollo Connector as the track input.
2. Reopen the project in Apollo.
3. While loading the project, send notes via Apollo Connector.
4. Crash... maybe... hopefully...

### Your setup
Apollo 1.8.13

**Comment by mat1jaczyyy** [comment]
repro'd

**Comment by mat1jaczyyy** [comment]
happens on regular midi input as well
