### ISSUE TITLE
Apollo Connector doesn't load correctly in Ableton Live on Apple Silicon

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#467]
Check Apollo Connector issue when loading it into Live running natively on Apple Silicon.
Possibly add missing Apple Silicon support if that's the case.

Refer to [this message](https://discord.com/channels/507570322833408011/605235030385623060/1201193632498196630) in the Apollo Studio Discord server.

**Comment by mat1jaczyyy** [comment]
sadam lib is outdated, should be a relatively easy fix

**Comment by mat1jaczyyy** [comment]
Resolved by https://github.com/mat1jaczyyy/apollo-studio/commit/24dc4dd948e38e21672dedf798db56bdfdae903b
