### ISSUE TITLE
Asking for permission to use images shown on website

### ISSUE THREAD

**Issue by nick-phenow** [mat1jaczyyy/apollo-studio#477]
I am making a Wikipedia page covering this program, I was wondering if i could use the images shown on the apollo studio website. Also it would be greatly appreciated if you included any copyright or creative commons information.

**Comment by mat1jaczyyy** [comment]
There's a [License](https://github.com/mat1jaczyyy/apollo-studio/tree/master/LICENSE) that covers software I guess...

You may use any assets you like for this purpose. Maybe [Assets folder](https://github.com/mat1jaczyyy/apollo-studio/tree/master/Assets) can also help you?

**Comment by nick-phenow** [comment]
Thank you very much
