### ISSUE TITLE
Side buttons don't work

### ISSUE THREAD

**Issue by TrizekYT** [mat1jaczyyy/apollo-studio#5]
**Describe the bug**
the right, left, and bottom side circle buttons do not do anything on the launchpad 

**To Reproduce**
press one of the circle buttons on the left right or bottom sides

**Expected behavior**
I thought it was supposed to make a light appear somewhere else like the other buttons did

**Screenshots**
![win_20181115_13_19_42_pro](https://user-images.githubusercontent.com/45077321/48573051-26205300-e8d9-11e8-8a7a-6acd392ed9e9.jpg)

**Your setup**
Windows 10

**Additional context**
idk if this is an issue but I hope it helps

**Comment by TrizekYT** [comment]
Launchpad Pro

**Comment by mat1jaczyyy** [comment]
Custom or Stock firmware? Which mode are you using on the LP?

**Comment by TrizekYT** [comment]
custom

**Comment by TrizekYT** [comment]
performance mode

**Comment by mat1jaczyyy** [comment]
Confirmed to work on my Launchpad. Update your firmware and enable XY layout in setup.
