### ISSUE TITLE
Allow user to select a MIDI port

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#6]
Bug:
Apollo selects wrong MIDI port, can't change it, therefore, can't use it.

Reproduce:
Connect 1 x MIDI Keyboard, 1 x Zoom U-44 Audio Interface and 1 x Launchpad Pro (CFW) (jk, but thats my setup) and try to get MIDI/Light feedback.

Expected behaviour:
Obviously either selecting the right MIDI port on startup or manually be able to select ports.

Setup:
Windows 10 Build 10240, Zoom U-44, Launchpad Pro CFW, MIDI Keyboard

**Comment by mat1jaczyyy** [comment]
Yes, Apollo needs a port selector.

**Comment by vaaski** [comment]
@mat1jaczyyy don't forget to write documentation on the range and communication of the port.

**Comment by mat1jaczyyy** [comment]
eww docs. eh, I'll do it no worries

**Comment by mat1jaczyyy** [comment]
I've implemented the necessary requests in the api. Up to vaaski to create UI elements for them and call into them.

**Comment by mat1jaczyyy** [comment]
Port changer implemented by @vaaski in 8d5a1f10e85eedf40cbfae8f4f056e07b198fdf4
