### ISSUE TITLE
Crash when saving with no port

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#64]
### Description
Apollo crashes when saving a non-empty project file.

### To Reproduce
Create project, open track and insert any effect (tested with Preview and Fade).
Save project. Upon choosing project name and clicking save the crash occurs.

### Expected behavior
No crash.

### Screenshots
-

### Your setup
Windows 10 (1803)
Apollo Build 12 (d3c4b07)

### Additional context
```Exception has occurred: CLR/System.NullReferenceException
Eine Ausnahme vom Typ "System.NullReferenceException" ist in Apollo.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.: 'Object reference not set to an instance of an object.'
   bei Apollo.Elements.Track.Encode() in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Elements\Track.cs: Zeile103
   bei Apollo.Elements.Project.Encode() in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Elements\Project.cs: Zeile165
   bei Apollo.Elements.Project.<Save>d__20.MoveNext() in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Elements\Project.cs: Zeile71```

**Comment by mat1jaczyyy** [comment]
Can't reproduce, do you have a Track that's missing a Launchpad port?

**Comment by rpgaleksy** [comment]
Yes, indeed. Forgot that, empty port while saving.

**Comment by mat1jaczyyy** [comment]
Reproduced.
