### ISSUE TITLE
Crash when (deleted) Copy random loop is not done upon closing project

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#65]
### Description
Apollo crashes when a Copy with random loop is deleted before it has finished and the project is closed.

### To Reproduce
Create Copy with random loop. No need for offsets or Loop checkbox. Set rate knob to subdivision mode (any subdivision should work). Trigger and hold any note, delete copy and close the project.

### Expected behavior
No crash.

### Screenshots
-

### Your setup
Windows 10 (1803)
Apollo Build 12 (c960153)

### Additional context
```Exception has occurred: CLR/System.NullReferenceException
Eine Ausnahme vom Typ "System.NullReferenceException" ist in Apollo.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.: 'Object reference not set to an instance of an object.'
   bei Apollo.Structures.Length.op_Implicit(Length x) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Structures\Length.cs: Zeile34
   bei Apollo.Devices.Copy.HandleRandomLoop(Signal original, List`1 offsets) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Devices\Copy.cs: Zeile151
   bei Apollo.Devices.Copy.Tick(Object sender, EventArgs e) in C:\Users\Aleks.L\Documents\GitHub\apollo-studio\Apollo\Devices\Copy.cs: Zeile115
   bei System.Timers.Timer.MyTimerCallback(Object state)```

**Comment by mat1jaczyyy** [comment]
Can't reproduce this, can you provide exact steps?

**Comment by rpgaleksy** [comment]
Edited.

**Comment by rpgaleksy** [comment]
Edited again, this time repro should work.

**Comment by mat1jaczyyy** [comment]
Reproduced.
