### ISSUE TITLE
First request takes a few seconds to respond

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#7]
The first request towards the API takes a while to return a response. This should be fixed by adding a stub handshake request on init.

**Comment by mat1jaczyyy** [comment]
@vaaski: when you catch some time, you should implement the handshake towards the API.

Sending an empty request towards :1548/api after receiving the api's request to :1549/init will do. Note that you don't want to send a response towards the request to /init, but rather make a new request.

The api's response will be an empty 200 OK.

**Comment by vaaski** [comment]
![image](https://user-images.githubusercontent.com/17879327/48644178-19d3ed00-e9e2-11e8-90c9-fb167834f6b7.png)
The api responds with 500 to an empty post to `/api`

**Comment by mat1jaczyyy** [comment]
![image](https://user-images.githubusercontent.com/13300194/48644242-4f78d600-e9e2-11e8-8a3e-94503871416c.png)

**Comment by mat1jaczyyy** [comment]
ahem. check response tab?

**Comment by vaaski** [comment]
response is empty.

you were so confident too haha
![image](https://user-images.githubusercontent.com/17879327/48644334-89e27300-e9e2-11e8-9cf3-216711d6ac01.png)
