### ISSUE TITLE
The ability to drag device(s) to a group.

### ISSUE THREAD

**Issue by TruffleLaunchpad** [mat1jaczyyy/apollo-studio#72]
I'm requesting the feature to drag device(s) in and possibly out of a group. So let's say that I created a light chain and forgot to create it in the group, I'd want to be able to drag that chain into the group without having to create a chain within that group.

**Comment by mat1jaczyyy** [comment]
This is part of #37  which covers all currently unimplemented features regarding selection, dragging and device operations.
