### ISSUE TITLE
Too long Chain/Track names expand the size of their container

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#77]
They should be cutting the Text with "..." instead.

**Comment by rpgaleksy** [comment]
Consider (too) long chain names that don't fit inside the group viewer and being able to still view the full chain name.
Maybe have an info popup showing the full name after x ms mouseover on a chain.

**Comment by mat1jaczyyy** [comment]
Avalonia hasn't implemented TextTrimming yet. Part of https://github.com/AvaloniaUI/Avalonia/pull/1950, this will be fixed without the ellipsis.
