### ISSUE TITLE
Enhanced workspace instead of tracks

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#79]
### Is your feature request related to a problem? Please describe.
no ( ͡° ͜ʖ ͡°)

### Describe the solution you'd like
Instead of tracks, have a workspace editor that lets you arrange Launchpads in IRL configuration and have devices work within that arrangement. You know what I mean, we talked about it, you came up with it.

### Describe alternatives you've considered
Leave it like that. Maybe you don't want to kill yourself idk.

### Additional context
_ohnothepreview~_
(This is not a particularly serious issue but if you manage to do it somehow in x years in Apollo version y, I'm down.)

**Comment by mat1jaczyyy** [comment]
While it would be extremely helpful in solving cross-Launchpad effects, this goes heavily against the current Apollo design pattern. Way too much of the application would have to be changed, to the point where it's almost not Apollo anymore.

This idea could be considered for an entirely different project, though.
