### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#8]
The app takes a while waiting for the api to initialize at the start. Maybe draw a splash screen in the meantime?

**Comment by vaaski** [comment]
unsure how one would achieve this, but two things:
- the window doesn't get created until API requests `/init`, I could change it to create instantly and hide until the request
- other than that, electron [actually recommends](https://electronjs.org/docs/api/browser-window#showing-window-gracefully) to wait until the window fired "ready-to-show", so best we can do is exactly that so you wouldn't see an empty apollo or we could show a loading window as discord does, but that wouldn't improve much for now I think.

**Comment by mat1jaczyyy** [comment]
is it possible to create a second, separate window for this and close it when the api reports as initialized?

**Comment by mat1jaczyyy** [comment]
as part of the switch to Avalonia, this will be implemented.

**Comment by mat1jaczyyy** [comment]
The new UI fully fixes this problem.
