### ISSUE TITLE
Pattern midi import 

### ISSUE THREAD

**Issue by DenkingOfficial** [mat1jaczyyy/apollo-studio#89]
### Description
Crash when importing midi files to Pattern device.

### To Reproduce
Create pattern and Import any .mid file

### Expected behavior
No crash

### Screenshots
-

### Your setup
Windows 10 (x64), Apollo-b1

### Additional context
Hey mom, I'm a Beta tester

**Comment by mat1jaczyyy** [comment]
I cannot reproduce this crash. Can you send attach a MIDI file here that does reproduce the crash? Thanks

**Comment by r3apst3p** [comment]
![123](https://user-images.githubusercontent.com/48379113/58042439-650eba00-7b43-11e9-8294-36a6f31869cf.gif)

**Comment by mat1jaczyyy** [comment]
Still can't repro.
![image](https://user-images.githubusercontent.com/13300194/58042572-54f2dc80-7b3b-11e9-8720-8700daa1c667.png)

**Comment by DenkingOfficial** [comment]
Crashdump
[crashdump-Midi-Import.zip](https://github.com/mat1jaczyyy/apollo-studio/files/3217169/crashdump-Midi-Import.zip)
