### ISSUE TITLE
Crash when dragging Device onto ScrollBar

### ISSUE THREAD

**Issue by M4kI9H7** [mat1jaczyyy/apollo-studio#96]
### Description
Drag&Dropping any devices into group's chain(or device wrappers) will cause crash

### To Reproduce
Drag&Drop any devices into group device

### Expected behavior
Not crashing.

### Screenshots
No screenshots, the crash dump is attached below.

### Your setup
apollo-b3, Windows 10

### Additional context
[crashdump-1558872248-exception.log](https://github.com/mat1jaczyyy/apollo-studio/files/3220295/crashdump-1558872248-exception.log)

**Comment by mat1jaczyyy** [comment]
Reproduced.
